---
apiVersion: v1
kind: Service
metadata:
  name: social-graph
  labels:
    microless: social-network
    app.kubernetes.io/name: social-graph
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: social-graph-service
    app.kubernetes.io/part-of: social-network
  namespace: social-network
spec:
  ports:
  - port: 8080
    name: grpc
    targetPort: grpc
  - port: 8081
    name: rest
    targetPort: rest
  selector:
    microless: social-network
    app.kubernetes.io/name: social-graph
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: social-graph
    app.kubernetes.io/part-of: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph
  labels:
    microless: social-network
    app.kubernetes.io/name: social-graph
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: social-graph-deployment
    app.kubernetes.io/part-of: social-network
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      microless: social-network
      app.kubernetes.io/name: social-graph
      app.kubernetes.io/instance: k8s-deploy
      app.kubernetes.io/component: social-graph
      app.kubernetes.io/part-of: social-network
  template:
    metadata:
      labels:
        microless: social-network
        app.kubernetes.io/name: social-graph
        app.kubernetes.io/instance: k8s-deploy
        app.kubernetes.io/component: social-graph
        app.kubernetes.io/part-of: social-network
      name: social-graph
    spec:
      containers:
      - name: server
        image: microless/socialgraph:0.1.2
        ports:
        - name: grpc
          containerPort: 8080
        - name: rest
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json