apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    microless: social-network
    app.kubernetes.io/name: service-gateway
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: service-ingress
    app.kubernetes.io/part-of: social-network
  name: ingress
  namespace: social-network
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: gateway
            port:
              number: 8081