// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/plot.proto

package plot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlotServiceClient is the client API for PlotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlotServiceClient interface {
	WritePlot(ctx context.Context, in *WritePlotRequest, opts ...grpc.CallOption) (*WritePlotRespond, error)
	ReadPlot(ctx context.Context, in *ReadPlotRequest, opts ...grpc.CallOption) (*ReadPlotRespond, error)
}

type plotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlotServiceClient(cc grpc.ClientConnInterface) PlotServiceClient {
	return &plotServiceClient{cc}
}

func (c *plotServiceClient) WritePlot(ctx context.Context, in *WritePlotRequest, opts ...grpc.CallOption) (*WritePlotRespond, error) {
	out := new(WritePlotRespond)
	err := c.cc.Invoke(ctx, "/microless.media.plot.PlotService/WritePlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plotServiceClient) ReadPlot(ctx context.Context, in *ReadPlotRequest, opts ...grpc.CallOption) (*ReadPlotRespond, error) {
	out := new(ReadPlotRespond)
	err := c.cc.Invoke(ctx, "/microless.media.plot.PlotService/ReadPlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlotServiceServer is the server API for PlotService service.
// All implementations must embed UnimplementedPlotServiceServer
// for forward compatibility
type PlotServiceServer interface {
	WritePlot(context.Context, *WritePlotRequest) (*WritePlotRespond, error)
	ReadPlot(context.Context, *ReadPlotRequest) (*ReadPlotRespond, error)
	mustEmbedUnimplementedPlotServiceServer()
}

// UnimplementedPlotServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlotServiceServer struct {
}

func (UnimplementedPlotServiceServer) WritePlot(context.Context, *WritePlotRequest) (*WritePlotRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WritePlot not implemented")
}
func (UnimplementedPlotServiceServer) ReadPlot(context.Context, *ReadPlotRequest) (*ReadPlotRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlot not implemented")
}
func (UnimplementedPlotServiceServer) mustEmbedUnimplementedPlotServiceServer() {}

// UnsafePlotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlotServiceServer will
// result in compilation errors.
type UnsafePlotServiceServer interface {
	mustEmbedUnimplementedPlotServiceServer()
}

func RegisterPlotServiceServer(s grpc.ServiceRegistrar, srv PlotServiceServer) {
	s.RegisterService(&PlotService_ServiceDesc, srv)
}

func _PlotService_WritePlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WritePlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlotServiceServer).WritePlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microless.media.plot.PlotService/WritePlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlotServiceServer).WritePlot(ctx, req.(*WritePlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlotService_ReadPlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlotServiceServer).ReadPlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microless.media.plot.PlotService/ReadPlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlotServiceServer).ReadPlot(ctx, req.(*ReadPlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlotService_ServiceDesc is the grpc.ServiceDesc for PlotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microless.media.plot.PlotService",
	HandlerType: (*PlotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WritePlot",
			Handler:    _PlotService_WritePlot_Handler,
		},
		{
			MethodName: "ReadPlot",
			Handler:    _PlotService_ReadPlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plot.proto",
}
