// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/castinfo.proto

package castinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	proto "microless/media/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteCastInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender bool   `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Intro  string `protobuf:"bytes,3,opt,name=intro,proto3" json:"intro,omitempty"`
}

func (x *WriteCastInfoRequest) Reset() {
	*x = WriteCastInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_castinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteCastInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCastInfoRequest) ProtoMessage() {}

func (x *WriteCastInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_castinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCastInfoRequest.ProtoReflect.Descriptor instead.
func (*WriteCastInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_castinfo_proto_rawDescGZIP(), []int{0}
}

func (x *WriteCastInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WriteCastInfoRequest) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *WriteCastInfoRequest) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

type WriteCastInfoRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CastInfoId string `protobuf:"bytes,1,opt,name=cast_info_id,json=castInfoId,proto3" json:"cast_info_id,omitempty"`
}

func (x *WriteCastInfoRespond) Reset() {
	*x = WriteCastInfoRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_castinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteCastInfoRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCastInfoRespond) ProtoMessage() {}

func (x *WriteCastInfoRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_castinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCastInfoRespond.ProtoReflect.Descriptor instead.
func (*WriteCastInfoRespond) Descriptor() ([]byte, []int) {
	return file_proto_castinfo_proto_rawDescGZIP(), []int{1}
}

func (x *WriteCastInfoRespond) GetCastInfoId() string {
	if x != nil {
		return x.CastInfoId
	}
	return ""
}

type ReadCastInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CastIds []string `protobuf:"bytes,1,rep,name=cast_ids,json=castIds,proto3" json:"cast_ids,omitempty"`
}

func (x *ReadCastInfoRequest) Reset() {
	*x = ReadCastInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_castinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCastInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCastInfoRequest) ProtoMessage() {}

func (x *ReadCastInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_castinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCastInfoRequest.ProtoReflect.Descriptor instead.
func (*ReadCastInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_castinfo_proto_rawDescGZIP(), []int{2}
}

func (x *ReadCastInfoRequest) GetCastIds() []string {
	if x != nil {
		return x.CastIds
	}
	return nil
}

type ReadCastInfoRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CastInfos []*proto.CastInfo `protobuf:"bytes,1,rep,name=cast_infos,json=castInfos,proto3" json:"cast_infos,omitempty"`
}

func (x *ReadCastInfoRespond) Reset() {
	*x = ReadCastInfoRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_castinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCastInfoRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCastInfoRespond) ProtoMessage() {}

func (x *ReadCastInfoRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_castinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCastInfoRespond.ProtoReflect.Descriptor instead.
func (*ReadCastInfoRespond) Descriptor() ([]byte, []int) {
	return file_proto_castinfo_proto_rawDescGZIP(), []int{3}
}

func (x *ReadCastInfoRespond) GetCastInfos() []*proto.CastInfo {
	if x != nil {
		return x.CastInfos
	}
	return nil
}

var File_proto_castinfo_proto protoreflect.FileDescriptor

var file_proto_castinfo_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f,
	0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x58, 0x0a, 0x14, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x61, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x22, 0x38, 0x0a, 0x14,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x61, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64,
	0x43, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12,
	0x38, 0x0a, 0x0a, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x63, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x32, 0xf0, 0x01, 0x0a, 0x0f, 0x43, 0x61,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a,
	0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43,
	0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x43,
	0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x6c,
	0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e,
	0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x42, 0x20, 0x5a, 0x1e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_castinfo_proto_rawDescOnce sync.Once
	file_proto_castinfo_proto_rawDescData = file_proto_castinfo_proto_rawDesc
)

func file_proto_castinfo_proto_rawDescGZIP() []byte {
	file_proto_castinfo_proto_rawDescOnce.Do(func() {
		file_proto_castinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_castinfo_proto_rawDescData)
	})
	return file_proto_castinfo_proto_rawDescData
}

var file_proto_castinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_castinfo_proto_goTypes = []interface{}{
	(*WriteCastInfoRequest)(nil), // 0: microless.media.castinfo.WriteCastInfoRequest
	(*WriteCastInfoRespond)(nil), // 1: microless.media.castinfo.WriteCastInfoRespond
	(*ReadCastInfoRequest)(nil),  // 2: microless.media.castinfo.ReadCastInfoRequest
	(*ReadCastInfoRespond)(nil),  // 3: microless.media.castinfo.ReadCastInfoRespond
	(*proto.CastInfo)(nil),       // 4: microless.media.CastInfo
}
var file_proto_castinfo_proto_depIdxs = []int32{
	4, // 0: microless.media.castinfo.ReadCastInfoRespond.cast_infos:type_name -> microless.media.CastInfo
	0, // 1: microless.media.castinfo.CastInfoService.WriteCastInfo:input_type -> microless.media.castinfo.WriteCastInfoRequest
	2, // 2: microless.media.castinfo.CastInfoService.ReadCastInfo:input_type -> microless.media.castinfo.ReadCastInfoRequest
	1, // 3: microless.media.castinfo.CastInfoService.WriteCastInfo:output_type -> microless.media.castinfo.WriteCastInfoRespond
	3, // 4: microless.media.castinfo.CastInfoService.ReadCastInfo:output_type -> microless.media.castinfo.ReadCastInfoRespond
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_castinfo_proto_init() }
func file_proto_castinfo_proto_init() {
	if File_proto_castinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_castinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteCastInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_castinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteCastInfoRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_castinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCastInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_castinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCastInfoRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_castinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_castinfo_proto_goTypes,
		DependencyIndexes: file_proto_castinfo_proto_depIdxs,
		MessageInfos:      file_proto_castinfo_proto_msgTypes,
	}.Build()
	File_proto_castinfo_proto = out.File
	file_proto_castinfo_proto_rawDesc = nil
	file_proto_castinfo_proto_goTypes = nil
	file_proto_castinfo_proto_depIdxs = nil
}
