apiVersion: v1
kind: Service
metadata:
  name: compose-post-serverless
  namespace: social-network
spec:
  selector:
    app: compose-post
    type: serverless
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-serverless
  namespace: social-network
spec:
  replicas: 0
  selector:
    matchLabels:
      app: compose-post
      type: serverless
  template:
    metadata:
      labels:
        app: compose-post
        type: serverless
      name: compose-post-serverless
      namespace: social-network
    spec:
      nodeSelector:
        type: serverless
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-composepost:0.3.5
        ports:
        - name: grpc
          containerPort: 8080
        - name: stats
          containerPort: 9000
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/lb/config.json"
        - name: SERVICE_ADDR
          value: ":8080"
        - name: STATS_ADDR
          value: ":9000"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: lb-config
          mountPath: "/lb"
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.json
            path: config.json
      - name: lb-config
        configMap:
          name: compose-post-lb-config
          items:
          - key: lb-serverless.json
            path: config.json
