apiVersion: v1
kind: Service
metadata:
  name: text-serverless
  namespace: social-network
spec:
  clusterIP: None
  selector:
    app: text
    type: serverless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-serverless
  namespace: social-network
spec:
  selector:
    matchLabels:
      app: text
      type: serverless
  template:
    metadata:
      labels:
        app: text
        type: serverless
      name: text-serverless
      namespace: social-network
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-text:0.2.0
        ports:
        - name: grpc
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
            - key: lb-serverless.json
              path: lb.json
