apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: social-network-kn
data:
  config.json: |
    {
      "grpc": ":8080",
      "rest": ":8081",
      "otel": "jaeger.jaeger:4317",
      "mongodb": {
        "url": "mongodb://mongodb.mongodb:27017",
        "database": "social-network"
      },
      "redis": {
        "usertimeline": "redis://redis.social-network-backend:6379/0",
        "socialgraph": "redis://redis.social-network-backend:6379/1",
        "hometimeline": "redis://redis.social-network-backend:6379/2",
        "poststorage": "redis://redis.social-network-backend:6379/3",
        "user": "redis://redis.social-network-backend:6379/4",
        "urlshorten": "redis://redis.social-network-backend:6379/5"
      },
      "service": {
        "poststorage": "post-storage.social-network-kn.svc.cluster.local:80",
        "usertimeline": "user-timeline.social-network-kn.svc.cluster.local:80",
        "user": "user.social-network-kn.svc.cluster.local:80",
        "socialgraph": "social-graph.social-network-kn.svc.cluster.local:80",
        "hometimeline": "home-timeline.social-network-kn.svc.cluster.local:80",
        "media": "media.social-network-kn.svc.cluster.local:80",
        "urlshorten": "url-shorten.social-network-kn.svc.cluster.local:80",
        "usermention": "user-mention.social-network-kn.svc.cluster.local:80",
        "text": "text.social-network-kn.svc.cluster.local:80",
        "composepost": "compose-post.social-network-kn.svc.cluster.local:80"
      },
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }