apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway
  namespace: social-network-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-gateway:0.1.7
        ports:
        - name: http1
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json