apiVersion: v1
kind: Namespace
metadata:
  name: social-network-kn-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
  namespace: social-network-kn-test
data:
  config.json: |
    {
      "grpc": ":8080",
      "rest": ":8081",
      "otel": "jaeger.jaeger:4317",
      "mongodb": {
        "url": "mongodb://mongodb.mongodb:27017",
        "database": "social-network"
      },
      "redis": {
        "usertimeline": "redis://redis.redis:6379/0",
        "socialgraph": "redis://redis.redis:6379/1",
        "hometimeline": "redis://redis.redis:6379/2",
        "poststorage": "redis://redis.redis:6379/3",
        "user": "redis://redis.redis:6379/4",
        "urlshorten": "redis://redis.redis:6379/5"
      },
      "service": {
        "poststorage": "post-storage.social-network-kn.svc.cluster.local:80",
        "usertimeline": "user-timeline.social-network-kn.svc.cluster.local:80",
        "user": "user.social-network-kn.svc.cluster.local:80",
        "socialgraph": "social-graph.social-network-kn.svc.cluster.local:80",
        "hometimeline": "home-timeline.social-network-kn.svc.cluster.local:80",
        "media": "media.social-network-kn.svc.cluster.local:80",
        "urlshorten": "url-shorten.social-network-kn.svc.cluster.local:80",
        "usermention": "user-mention.social-network-kn.svc.cluster.local:80",
        "text": "text.social-network-kn.svc.cluster.local:80",
        "composepost": "compose-post.social-network-kn.svc.cluster.local:80"
      },
      "gateway": "gateway.social-network-kn.10.2.64.8.sslip.io:80",
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: social-network-kn-test
spec:
  template:
    spec:
      containers:
      - name: test
        image: waterlemongan/microless-socialnetwork-test:0.1.7
        env:
        - name: TEST_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config-test
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config-test
          configMap:
            name: config-test
            items:
            - key: config.json
              path: config.json
      restartPolicy: Never
  backoffLimit: 0