apiVersion: v1
kind: Service
metadata:
  name: home-timeline
  namespace: social-network
spec:
  ports:
  - port: 8080
    name: grpc
    targetPort: grpc
  selector:
    app: home-timeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline
  namespace: social-network
spec:
  selector:
    matchLabels:
      app: home-timeline
  template:
    metadata:
      labels:
        app: home-timeline
      name: home-timeline
      namespace: social-network
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-hometimeline:0.1.8
        ports:
        - name: grpc
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
