apiVersion: v1
kind: Service
metadata:
  name: user-mention
  namespace: social-network
spec:
  ports:
  - port: 8080
    name: grpc
    targetPort: grpc
  selector:
    app: user-mention
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mention
  namespace: social-network
spec:
  selector:
    matchLabels:
      app: user-mention
  template:
    metadata:
      labels:
        app: user-mention
      name: user-mention
      namespace: social-network
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-usermention:0.1.8
        ports:
        - name: grpc
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json