apiVersion: v1
kind: Namespace
metadata:
  name: mapreduce-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
  namespace: mapreduce-test
data:
  config.json: |
    {
      "rest": ":8080",
      "minio": {
          "url": "minio.minio:9000",
          "access_key": "minioadmin",
          "secret_key": "minioadmin",
          "secure": false
      },
      "service": {
          "mapreduce": "http://mapreduce.mapreduce:8080/",
          "file": "http://file.mapreduce:8080/",
          "mapper": "http://mapper.mapreduce:8080/",
          "reducer": "http://reducer.mapreduce:8080/"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: mapreduce-test
spec:
  template:
    spec:
      containers:
      - name: test
        image: waterlemongan/microless-mapreduce-test:0.1.0
        env:
        - name: TEST_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config-test
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config-test
          configMap:
            name: config-test
            items:
            - key: config.json
              path: config.json
      restartPolicy: Never
  backoffLimit: 0