apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: pingpong
data:
  config.json: |
    {
      "service": {
        "ping": "ping:8080",
        "pong": "pong:8080"
      }
    }
  lb.json: |
    {
      "server": {
        "enable": true,
        "update_interval": 1,
        "update_ratio": 0.5
      },
      "client": {
        "enable": true,
        "vm_postfix": "-vm",
        "serverless_postfix": "-serverless",
        "update_interval": 1,
        "retry": 3,
        "service_rate_limit": {
          "ping": 10,
          "pong": 10
        },
        "local_services": {},
        "redis_addr": "redis://redis.redis:6379/7"
      },
      "serverless": {
        "enable": false
      }
    }
  lb-gateway.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": true,
        "vm_postfix": "-vm",
        "serverless_postfix": "-serverless",
        "update_interval": 1,
        "retry": 3,
        "service_rate_limit": {
          "ping": 10,
          "pong": 10
        },
        "local_services": {},
        "redis_addr": "redis://redis.redis:6379/7"
      },
      "serverless": {
        "enable": false
      }
    }
