apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mapreduce
  labels:
    microless: mapreduce
    app.kubernetes.io/name: mapreduce
    app.kubernetes.io/instance: kn-deploy
    app.kubernetes.io/component: mapreduce-service
    app.kubernetes.io/part-of: mapreduce
    networking.knative.dev/visibility: cluster-local
  namespace: mapreduce-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-mapreduce-mapreduce:0.1.0
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json