# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import castinfo_pb2 as proto_dot_castinfo__pb2


class CastInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteCastInfo = channel.unary_unary(
                '/microless.media.castinfo.CastInfoService/WriteCastInfo',
                request_serializer=proto_dot_castinfo__pb2.WriteCastInfoRequest.SerializeToString,
                response_deserializer=proto_dot_castinfo__pb2.WriteCastInfoRespond.FromString,
                )
        self.ReadCastInfo = channel.unary_unary(
                '/microless.media.castinfo.CastInfoService/ReadCastInfo',
                request_serializer=proto_dot_castinfo__pb2.ReadCastInfoRequest.SerializeToString,
                response_deserializer=proto_dot_castinfo__pb2.ReadCastInfoRespond.FromString,
                )


class CastInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteCastInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCastInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CastInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteCastInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteCastInfo,
                    request_deserializer=proto_dot_castinfo__pb2.WriteCastInfoRequest.FromString,
                    response_serializer=proto_dot_castinfo__pb2.WriteCastInfoRespond.SerializeToString,
            ),
            'ReadCastInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCastInfo,
                    request_deserializer=proto_dot_castinfo__pb2.ReadCastInfoRequest.FromString,
                    response_serializer=proto_dot_castinfo__pb2.ReadCastInfoRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.media.castinfo.CastInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CastInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteCastInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.castinfo.CastInfoService/WriteCastInfo',
            proto_dot_castinfo__pb2.WriteCastInfoRequest.SerializeToString,
            proto_dot_castinfo__pb2.WriteCastInfoRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadCastInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.castinfo.CastInfoService/ReadCastInfo',
            proto_dot_castinfo__pb2.ReadCastInfoRequest.SerializeToString,
            proto_dot_castinfo__pb2.ReadCastInfoRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
