# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/castinfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/castinfo.proto\x12\x18microless.media.castinfo\x1a\x10proto/data.proto\"C\n\x14WriteCastInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x08\x12\r\n\x05intro\x18\x03 \x01(\t\",\n\x14WriteCastInfoRespond\x12\x14\n\x0c\x63\x61st_info_id\x18\x01 \x01(\t\"\'\n\x13ReadCastInfoRequest\x12\x10\n\x08\x63\x61st_ids\x18\x01 \x03(\t\"D\n\x13ReadCastInfoRespond\x12-\n\ncast_infos\x18\x01 \x03(\x0b\x32\x19.microless.media.CastInfo2\xf0\x01\n\x0f\x43\x61stInfoService\x12o\n\rWriteCastInfo\x12..microless.media.castinfo.WriteCastInfoRequest\x1a..microless.media.castinfo.WriteCastInfoRespond\x12l\n\x0cReadCastInfo\x12-.microless.media.castinfo.ReadCastInfoRequest\x1a-.microless.media.castinfo.ReadCastInfoRespondB Z\x1emicroless/media/proto/castinfob\x06proto3')



_WRITECASTINFOREQUEST = DESCRIPTOR.message_types_by_name['WriteCastInfoRequest']
_WRITECASTINFORESPOND = DESCRIPTOR.message_types_by_name['WriteCastInfoRespond']
_READCASTINFOREQUEST = DESCRIPTOR.message_types_by_name['ReadCastInfoRequest']
_READCASTINFORESPOND = DESCRIPTOR.message_types_by_name['ReadCastInfoRespond']
WriteCastInfoRequest = _reflection.GeneratedProtocolMessageType('WriteCastInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITECASTINFOREQUEST,
  '__module__' : 'proto.castinfo_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.castinfo.WriteCastInfoRequest)
  })
_sym_db.RegisterMessage(WriteCastInfoRequest)

WriteCastInfoRespond = _reflection.GeneratedProtocolMessageType('WriteCastInfoRespond', (_message.Message,), {
  'DESCRIPTOR' : _WRITECASTINFORESPOND,
  '__module__' : 'proto.castinfo_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.castinfo.WriteCastInfoRespond)
  })
_sym_db.RegisterMessage(WriteCastInfoRespond)

ReadCastInfoRequest = _reflection.GeneratedProtocolMessageType('ReadCastInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _READCASTINFOREQUEST,
  '__module__' : 'proto.castinfo_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.castinfo.ReadCastInfoRequest)
  })
_sym_db.RegisterMessage(ReadCastInfoRequest)

ReadCastInfoRespond = _reflection.GeneratedProtocolMessageType('ReadCastInfoRespond', (_message.Message,), {
  'DESCRIPTOR' : _READCASTINFORESPOND,
  '__module__' : 'proto.castinfo_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.castinfo.ReadCastInfoRespond)
  })
_sym_db.RegisterMessage(ReadCastInfoRespond)

_CASTINFOSERVICE = DESCRIPTOR.services_by_name['CastInfoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036microless/media/proto/castinfo'
  _WRITECASTINFOREQUEST._serialized_start=68
  _WRITECASTINFOREQUEST._serialized_end=135
  _WRITECASTINFORESPOND._serialized_start=137
  _WRITECASTINFORESPOND._serialized_end=181
  _READCASTINFOREQUEST._serialized_start=183
  _READCASTINFOREQUEST._serialized_end=222
  _READCASTINFORESPOND._serialized_start=224
  _READCASTINFORESPOND._serialized_end=292
  _CASTINFOSERVICE._serialized_start=295
  _CASTINFOSERVICE._serialized_end=535
# @@protoc_insertion_point(module_scope)
