# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import composereview_pb2 as proto_dot_composereview__pb2


class ComposeReviewStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeReview = channel.unary_unary(
                '/microless.media.composereview.ComposeReview/ComposeReview',
                request_serializer=proto_dot_composereview__pb2.ComposeReviewRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ComposeReviewServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComposeReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComposeReviewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeReview': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeReview,
                    request_deserializer=proto_dot_composereview__pb2.ComposeReviewRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.media.composereview.ComposeReview', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComposeReview(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComposeReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.composereview.ComposeReview/ComposeReview',
            proto_dot_composereview__pb2.ComposeReviewRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
