# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/composereview.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/composereview.proto\x12\x1dmicroless.media.composereview\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"W\n\x14\x43omposeReviewRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x05\x32\x8f\x01\n\rComposeReview\x12~\n\rComposeReview\x12\x33.microless.media.composereview.ComposeReviewRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a\"\x15/api/v1/composereview:\x01*B%Z#microless/media/proto/composereviewb\x06proto3')



_COMPOSEREVIEWREQUEST = DESCRIPTOR.message_types_by_name['ComposeReviewRequest']
ComposeReviewRequest = _reflection.GeneratedProtocolMessageType('ComposeReviewRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEREVIEWREQUEST,
  '__module__' : 'proto.composereview_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.composereview.ComposeReviewRequest)
  })
_sym_db.RegisterMessage(ComposeReviewRequest)

_COMPOSEREVIEW = DESCRIPTOR.services_by_name['ComposeReview']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#microless/media/proto/composereview'
  _COMPOSEREVIEW.methods_by_name['ComposeReview']._options = None
  _COMPOSEREVIEW.methods_by_name['ComposeReview']._serialized_options = b'\202\323\344\223\002\032\"\025/api/v1/composereview:\001*'
  _COMPOSEREVIEWREQUEST._serialized_start=119
  _COMPOSEREVIEWREQUEST._serialized_end=206
  _COMPOSEREVIEW._serialized_start=209
  _COMPOSEREVIEW._serialized_end=352
# @@protoc_insertion_point(module_scope)
