# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import page_pb2 as proto_dot_page__pb2


class PageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadPage = channel.unary_unary(
                '/microless.media.page.PageService/ReadPage',
                request_serializer=proto_dot_page__pb2.ReadPageRequest.SerializeToString,
                response_deserializer=proto_dot_page__pb2.ReadPageRespond.FromString,
                )


class PageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadPage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPage,
                    request_deserializer=proto_dot_page__pb2.ReadPageRequest.FromString,
                    response_serializer=proto_dot_page__pb2.ReadPageRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.media.page.PageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.page.PageService/ReadPage',
            proto_dot_page__pb2.ReadPageRequest.SerializeToString,
            proto_dot_page__pb2.ReadPageRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
