# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/page.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/page.proto\x12\x14microless.media.page\x1a\x10proto/data.proto\x1a\x1cgoogle/api/annotations.proto\"N\n\x0fReadPageRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x14\n\x0creview_start\x18\x02 \x01(\x05\x12\x13\n\x0breview_stop\x18\x03 \x01(\x05\"\xa8\x01\n\x0fReadPageRespond\x12.\n\nmovie_info\x18\x01 \x01(\x0b\x32\x1a.microless.media.MovieInfo\x12-\n\ncast_infos\x18\x02 \x03(\x0b\x32\x19.microless.media.CastInfo\x12\x0c\n\x04plot\x18\x03 \x01(\t\x12(\n\x07reviews\x18\x04 \x03(\x0b\x32\x17.microless.media.Review2\x88\x01\n\x0bPageService\x12y\n\x08ReadPage\x12%.microless.media.page.ReadPageRequest\x1a%.microless.media.page.ReadPageRespond\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/page/{movie_id}B\x1cZ\x1amicroless/media/proto/pageb\x06proto3')



_READPAGEREQUEST = DESCRIPTOR.message_types_by_name['ReadPageRequest']
_READPAGERESPOND = DESCRIPTOR.message_types_by_name['ReadPageRespond']
ReadPageRequest = _reflection.GeneratedProtocolMessageType('ReadPageRequest', (_message.Message,), {
  'DESCRIPTOR' : _READPAGEREQUEST,
  '__module__' : 'proto.page_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.page.ReadPageRequest)
  })
_sym_db.RegisterMessage(ReadPageRequest)

ReadPageRespond = _reflection.GeneratedProtocolMessageType('ReadPageRespond', (_message.Message,), {
  'DESCRIPTOR' : _READPAGERESPOND,
  '__module__' : 'proto.page_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.page.ReadPageRespond)
  })
_sym_db.RegisterMessage(ReadPageRespond)

_PAGESERVICE = DESCRIPTOR.services_by_name['PageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032microless/media/proto/page'
  _PAGESERVICE.methods_by_name['ReadPage']._options = None
  _PAGESERVICE.methods_by_name['ReadPage']._serialized_options = b'\202\323\344\223\002\031\022\027/api/v1/page/{movie_id}'
  _READPAGEREQUEST._serialized_start=90
  _READPAGEREQUEST._serialized_end=168
  _READPAGERESPOND._serialized_start=171
  _READPAGERESPOND._serialized_end=339
  _PAGESERVICE._serialized_start=342
  _PAGESERVICE._serialized_end=478
# @@protoc_insertion_point(module_scope)
