# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/plot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/plot.proto\x12\x14microless.media.plot\" \n\x10WritePlotRequest\x12\x0c\n\x04plot\x18\x01 \x01(\t\"#\n\x10WritePlotRespond\x12\x0f\n\x07plot_id\x18\x01 \x01(\t\"\"\n\x0fReadPlotRequest\x12\x0f\n\x07plot_id\x18\x01 \x01(\t\"\x1f\n\x0fReadPlotRespond\x12\x0c\n\x04plot\x18\x01 \x01(\t2\xc4\x01\n\x0bPlotService\x12[\n\tWritePlot\x12&.microless.media.plot.WritePlotRequest\x1a&.microless.media.plot.WritePlotRespond\x12X\n\x08ReadPlot\x12%.microless.media.plot.ReadPlotRequest\x1a%.microless.media.plot.ReadPlotRespondB\x1cZ\x1amicroless/media/proto/plotb\x06proto3')



_WRITEPLOTREQUEST = DESCRIPTOR.message_types_by_name['WritePlotRequest']
_WRITEPLOTRESPOND = DESCRIPTOR.message_types_by_name['WritePlotRespond']
_READPLOTREQUEST = DESCRIPTOR.message_types_by_name['ReadPlotRequest']
_READPLOTRESPOND = DESCRIPTOR.message_types_by_name['ReadPlotRespond']
WritePlotRequest = _reflection.GeneratedProtocolMessageType('WritePlotRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEPLOTREQUEST,
  '__module__' : 'proto.plot_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.plot.WritePlotRequest)
  })
_sym_db.RegisterMessage(WritePlotRequest)

WritePlotRespond = _reflection.GeneratedProtocolMessageType('WritePlotRespond', (_message.Message,), {
  'DESCRIPTOR' : _WRITEPLOTRESPOND,
  '__module__' : 'proto.plot_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.plot.WritePlotRespond)
  })
_sym_db.RegisterMessage(WritePlotRespond)

ReadPlotRequest = _reflection.GeneratedProtocolMessageType('ReadPlotRequest', (_message.Message,), {
  'DESCRIPTOR' : _READPLOTREQUEST,
  '__module__' : 'proto.plot_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.plot.ReadPlotRequest)
  })
_sym_db.RegisterMessage(ReadPlotRequest)

ReadPlotRespond = _reflection.GeneratedProtocolMessageType('ReadPlotRespond', (_message.Message,), {
  'DESCRIPTOR' : _READPLOTRESPOND,
  '__module__' : 'proto.plot_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.plot.ReadPlotRespond)
  })
_sym_db.RegisterMessage(ReadPlotRespond)

_PLOTSERVICE = DESCRIPTOR.services_by_name['PlotService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032microless/media/proto/plot'
  _WRITEPLOTREQUEST._serialized_start=42
  _WRITEPLOTREQUEST._serialized_end=74
  _WRITEPLOTRESPOND._serialized_start=76
  _WRITEPLOTRESPOND._serialized_end=111
  _READPLOTREQUEST._serialized_start=113
  _READPLOTREQUEST._serialized_end=147
  _READPLOTRESPOND._serialized_start=149
  _READPLOTRESPOND._serialized_end=180
  _PLOTSERVICE._serialized_start=183
  _PLOTSERVICE._serialized_end=379
# @@protoc_insertion_point(module_scope)
