# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rating.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/rating.proto\x12\x16microless.media.rating\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"7\n\x13UploadRatingRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x05\x32\x7f\n\rRatingService\x12n\n\x0cUploadRating\x12+.microless.media.rating.UploadRatingRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/api/v1/rating:\x01*B\x1eZ\x1cmicroless/media/proto/ratingb\x06proto3')



_UPLOADRATINGREQUEST = DESCRIPTOR.message_types_by_name['UploadRatingRequest']
UploadRatingRequest = _reflection.GeneratedProtocolMessageType('UploadRatingRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADRATINGREQUEST,
  '__module__' : 'proto.rating_pb2'
  # @@protoc_insertion_point(class_scope:microless.media.rating.UploadRatingRequest)
  })
_sym_db.RegisterMessage(UploadRatingRequest)

_RATINGSERVICE = DESCRIPTOR.services_by_name['RatingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\034microless/media/proto/rating'
  _RATINGSERVICE.methods_by_name['UploadRating']._options = None
  _RATINGSERVICE.methods_by_name['UploadRating']._serialized_options = b'\202\323\344\223\002\023\"\016/api/v1/rating:\001*'
  _UPLOADRATINGREQUEST._serialized_start=105
  _UPLOADRATINGREQUEST._serialized_end=160
  _RATINGSERVICE._serialized_start=162
  _RATINGSERVICE._serialized_end=289
# @@protoc_insertion_point(module_scope)
