# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import rating_pb2 as proto_dot_rating__pb2


class RatingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadRating = channel.unary_unary(
                '/microless.media.rating.RatingService/UploadRating',
                request_serializer=proto_dot_rating__pb2.UploadRatingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class RatingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadRating': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadRating,
                    request_deserializer=proto_dot_rating__pb2.UploadRatingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.media.rating.RatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RatingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.rating.RatingService/UploadRating',
            proto_dot_rating__pb2.UploadRatingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
