# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import userreview_pb2 as proto_dot_userreview__pb2


class UserReviewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadUserReview = channel.unary_unary(
                '/microless.media.userreview.UserReviewService/UploadUserReview',
                request_serializer=proto_dot_userreview__pb2.UploadUserReviewRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ReadUserReviews = channel.unary_unary(
                '/microless.media.userreview.UserReviewService/ReadUserReviews',
                request_serializer=proto_dot_userreview__pb2.ReadUserReviewsRequest.SerializeToString,
                response_deserializer=proto_dot_userreview__pb2.ReadUserReviewsRespond.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/microless.media.userreview.UserReviewService/CreateUser',
                request_serializer=proto_dot_userreview__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class UserReviewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadUserReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUserReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadUserReview': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadUserReview,
                    request_deserializer=proto_dot_userreview__pb2.UploadUserReviewRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReadUserReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadUserReviews,
                    request_deserializer=proto_dot_userreview__pb2.ReadUserReviewsRequest.FromString,
                    response_serializer=proto_dot_userreview__pb2.ReadUserReviewsRespond.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_userreview__pb2.CreateUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.media.userreview.UserReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserReviewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadUserReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.userreview.UserReviewService/UploadUserReview',
            proto_dot_userreview__pb2.UploadUserReviewRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadUserReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.userreview.UserReviewService/ReadUserReviews',
            proto_dot_userreview__pb2.ReadUserReviewsRequest.SerializeToString,
            proto_dot_userreview__pb2.ReadUserReviewsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.media.userreview.UserReviewService/CreateUser',
            proto_dot_userreview__pb2.CreateUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
