apiVersion: v1
kind: Service
metadata:
  name: file
  labels:
    microless: mapreduce
    app.kubernetes.io/name: file
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: file-service
    app.kubernetes.io/part-of: mapreduce
  namespace: mapreduce
spec:
  ports:
  - port: 8080
    name: rest
    targetPort: rest
  selector:
    microless: mapreduce
    app.kubernetes.io/name: file
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: file
    app.kubernetes.io/part-of: mapreduce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  labels:
    microless: mapreduce
    app.kubernetes.io/name: file
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: file-deployment
    app.kubernetes.io/part-of: mapreduce
  namespace: mapreduce
spec:
  replicas: 1
  selector:
    matchLabels:
      microless: mapreduce
      app.kubernetes.io/name: file
      app.kubernetes.io/instance: k8s-deploy
      app.kubernetes.io/component: file
      app.kubernetes.io/part-of: mapreduce
  template:
    metadata:
      labels:
        microless: mapreduce
        app.kubernetes.io/name: file
        app.kubernetes.io/instance: k8s-deploy
        app.kubernetes.io/component: file
        app.kubernetes.io/part-of: mapreduce
      name: mapreduce
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-mapreduce-file:0.1.0
        ports:
        - name: rest
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger.jaeger:4318"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
