apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-config
  namespace: social-network
data:
  cas.json: |
    {
      "interval": 15,
      "stable_interval": 1,
      "namespace": "social-network",
      "ratio": 2,
      "max_delta": 10,
      "kube": {
        "vm_selector": "type=vm",
        "serverless_selector": "type=serverless"
      },
      "cluster": {
        "namespace": "social-network",
        "scale_up_latency": 1,
        "serverless_cpu": 0.25,
        "serverless_mem": 0.5,
        "vm_cpu": 12,
        "vm_mem": 48,
        "serverless_cpu_price": 0.000049,
        "serverless_mem_price": 0.00000613,
        "vm_price": 0.0006736667
      }
    }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler-role
  namespace: social-network
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "patch"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: social-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler-role-binding
  namespace: social-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-role
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: social-network
---
apiVersion: v1
kind: Pod
metadata:
  name: cluster-autoscaler
  namespace: social-network
spec:
  serviceAccountName: cluster-autoscaler
  nodeSelector:
    type: system
  containers:
  - name: cas
    image: waterlemongan/microless-cluster-autoscaler:0.1.0
    env:
    - name: CLUSTER_AUTOSCALER_CONFIG
      value: "/config/cas.json"
    volumeMounts:
    - name: config
      mountPath: "/config"
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: config
    configMap:
      name: cluster-autoscaler-config
      items:
      - key: cas.json
        path: cas.json

