apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: social-network
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  type: LoadBalancer
  selector:
    app: gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-lb-config
  namespace: social-network
data:
  lb-gateway.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": true,
        "degrade_interval": 1,
        "update_interval": 5,
        "vm_postfix": "-vm",
        "serverless_postfix": "-serverless",
        "retry": 3
      },
      "serverless": {
        "enable": false
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: social-network
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      name: gateway
      namespace: social-network
    spec:
      nodeSelector:
        type: system
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-gateway:0.3.1
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/lb/config.json"
        - name: SERVICE_ADDR
          value: ":8080"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: lb-config
          mountPath: "/lb"
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.json
            path: config.json
      - name: lb-config
        configMap:
          name: gateway-lb-config
          items:
          - key: lb-gateway.json
            path: config.json
