apiVersion: v1
kind: Namespace
metadata:
  name: social-network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoint-reader
  namespace: social-network
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-reader-binding
  namespace: social-network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: social-network
