apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: social-network-stats
  labels:
    release: prom
  namespace: social-network
spec:
  selector:
    matchLabels:
      type: stats
  endpoints:
  - port: stats
    interval: 5s
  namespaceSelector:
    matchNames:
    - social-network