FROM golang:1.18
# service to build
ARG SERVICES
# using go modules proxy in China
ARG GOPROXY="https://goproxy.cn"

WORKDIR /go/src
COPY . .
# build services, disable cgo
RUN for s in ${SERVICES}; do \
	cd $s && \
	go mod download && \
        CGO_ENABLED=0 go build -o /go/bin/$s cmd/main.go && \
	cd ..; \
    done
