FROM golang:1.18 as build
# using go modules proxy in China
ARG GOPROXY="https://goproxy.cn"

WORKDIR /go/src
COPY . .
RUN go mod download
# build restful gateway, disable cgo
RUN CGO_ENABLED=0 go build -o /go/bin/gateway gateway/cmd/main.go

FROM gcr.io/distroless/static-debian11
# path to the config file
ENV SERVICE_CONFIG="/config.json"

COPY --from=build /go/bin/gateway /server

EXPOSE 8081
CMD [ "/server" ]
