FROM golang:1.18 as build
# service to build
ARG SERVICES
ARG REST
# using go modules proxy in China
ARG GOPROXY="https://goproxy.cn"

WORKDIR /go/src
COPY . .
# build grpc services, disable cgo
RUN for s in ${SERVICES}; do \
        CGO_ENABLED=0 go build -o /go/bin/$s $s/cmd/grpc/main.go; \
    done
# build restful service proxies, disable cgo
RUN for s in ${SERVICES}; do \
        CGO_ENABLED=0 go build -o /go/bin/$s-rest $s/cmd/rest/main.go; \
    done