apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pong-vm-hpa
  namespace: pingpong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-vm
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: pong
      metric:
        name: grpc_server_request_per_second
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
