apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway
  labels:
    microless: media
    app.kubernetes.io/name: restful-gateway
    app.kubernetes.io/instance: kn-deploy
    app.kubernetes.io/component: restful-gateway-service
    app.kubernetes.io/part-of: media
  namespace: media-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: dev.local/microless/media-gateway:0.1.0
        ports:
        - name: http1
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json