apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    microless: social-network
    app.kubernetes.io/name: home-timeline
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: home-timeline-hpa
    app.kubernetes.io/part-of: social-network
  name: home-timeline-hpa
  namespace: social-network-lb-vm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: home-timeline
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80