apiVersion: v1
kind: Service
metadata:
  name: home-timeline-serverless
  namespace: social-network
spec:
  selector:
    app: home-timeline
    type: serverless
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-serverless
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-timeline
      type: serverless
  template:
    metadata:
      annotations:
        k8s.aliyun.com/eci-use-specs: "0.25-0.5Gi"
        k8s.aliyun.com/eci-image-cache: "true"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyCPULimit: 400m
        sidecar.istio.io/proxyMemory: 150Mi
        sidecar.istio.io/proxyMemoryLimit: 150Mi
#        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/includeOutboundPorts: "8080"
      labels:
        app: home-timeline
        type: serverless
        alibabacloud.com/eci: "true"
#        sidecar.istio.io/inject: "true"
      name: home-timeline-serverless
      namespace: social-network
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-hometimeline:0.3.10
        ports:
        - name: grpc
          containerPort: 8080
        - name: stats
          containerPort: 9000
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/lb/config.json"
        - name: SERVICE_ADDR
          value: ":8080"
        - name: STATS_ADDR
          value: ":9000"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: lb-config
          mountPath: "/lb"
          readOnly: true
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - name: post-storage
        image: waterlemongan/microless-socialnetwork-poststorage:0.3.10
        ports:
        - name: grpc
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/lb/config.json"
        - name: SERVICE_ADDR
          value: ":8081"
        - name: STATS_ADDR
          value: ":9001"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: lb-config
          mountPath: "/lb"
          readOnly: true
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.json
            path: config.json
      - name: lb-config
        configMap:
          name: home-timeline-lb-config
          items:
          - key: lb-serverless.json
            path: config.json
