apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: compose-post-kn
  labels:
    networking.knative.dev/visibility: cluster-local
  namespace: social-network
spec:
  template:
    spec:
      containers:
      - name: server
        image: dev.local/microless-socialnetwork-composepost:0.2.0
        ports:
        - name: h2c
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
            - key: lb-serverless.json
              path: lb.json
