apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: restful-gateway
  labels:
    microless: social-network
    app.kubernetes.io/name: restful-gateway
    app.kubernetes.io/instance: kn-deploy
    app.kubernetes.io/component: restful-gateway-kn-service
    app.kubernetes.io/part-of: social-network
    networking.knative.dev/visibility: cluster-local
  namespace: social-network-lb-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-gateway:0.1.7
        ports:
        - name: http1
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json