apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ping-serverless-hpa
  namespace: pingpong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-serverless
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: serverless_task_total
      target:
        type: AverageValue
        averageValue: "1"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
