# docker compose for development
version: '3'

services:
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=moviereview:redis:6379:0,userreview:redis:6379:1,castinfo:redis:6379:2,movieinfo:redis:6379:3,plot:redis:6379:4,reviewstorage:redis:6379:5,user:redis:6379:6
    ports:
      - 8082:8081

  redis:
    image: redis:6.2

  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/all-in-one:1.37
    command: ["--collector.otlp.enabled=true"]
    ports:
      - 16685:16685
      - 16686:16686

  gateway:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-gateway:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - compose-review
      - page
      - rating
      - user
      - user-review
    ports:
      - 8080:8080

  cast-info:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-castinfo:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - redis
      - mongodb
      - jaeger

  movie-info:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-movieinfo:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - movie-review
      - redis
      - mongodb
      - jaeger

  plot:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-plot:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - redis
      - mongodb
      - jaeger

  review-storage:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-reviewstorage:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - redis
      - mongodb
      - jaeger

  movie-review:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-moviereview:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - review-storage
      - redis
      - mongodb
      - jaeger

  user-review:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-userreview:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - review-storage
      - redis
      - mongodb
      - jaeger

  rating:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-rating:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - movie-info
      - jaeger

  compose-review:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-composereview:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - review-storage
      - user-review
      - movie-review
      - rating
      - jaeger

  user:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-user:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - user-review
      - redis
      - mongodb
      - jaeger

  page:
    environment:
      - SERVICE_ADDR=:8080
      - STATS_ADDR=:9000
    image: waterlemongan/microless-media-page:latest
    volumes:
      - ../config/dev.json:/config.json:ro
      - ../config/loadbalancer.json:/lb.json:ro
    depends_on:
      - movie-review
      - movie-info
      - cast-info
      - plot
      - jaeger
