prometheus:
  url: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
rules:
  default: false
  custom:
  - seriesQuery: 'grpc_server_request_total{namespace!="",pod!="",service!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
        service: {resource: "service"}
    name:
      matches: "^(.*)_total$"
      as: "${1}_per_second"
    metricsQuery: sum(irate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
  - seriesQuery: 'serverless_task_total{namespace!="",pod!="",service!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
        service: {resource: "service"}
    name:
      matches: "^(.*)$"
      as: "${1}"
    metricsQuery: avg(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
