apiVersion: v1
kind: Service
metadata:
  name: compose-post-vm
  namespace: social-network
spec:
  clusterIP: None
  selector:
    app: compose-post
    type: vm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-vm
  namespace: social-network
spec:
  selector:
    matchLabels:
      app: compose-post
      type: vm
  template:
    metadata:
      labels:
        app: compose-post
        type: vm
      name: compose-post-vm
      namespace: social-network
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-composepost:0.2.0
        ports:
        - name: grpc
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
            - key: lb.json
              path: lb.json
