apiVersion: v1
kind: Service
metadata:
  name: restful-gateway
  labels:
    microless: social-network
    app.kubernetes.io/name: restful-gateway
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: restful-gateway-vm-service
    app.kubernetes.io/part-of: social-network
  namespace: social-network-lb-vm
spec:
  ports:
  - port: 8081
    name: http
    targetPort: http
  selector:
    microless: social-network
    app.kubernetes.io/name: restful-gateway
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: restful-gateway-vm
    app.kubernetes.io/part-of: social-network
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restful-gateway
  labels:
    microless: social-network
    app.kubernetes.io/name: restful-gateway
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: restful-gateway-vm-deployment
    app.kubernetes.io/part-of: social-network
  namespace: social-network-lb-vm
spec:
  selector:
    matchLabels:
      microless: social-network
      app.kubernetes.io/name: restful-gateway
      app.kubernetes.io/instance: k8s-deploy
      app.kubernetes.io/component: restful-gateway-vm
      app.kubernetes.io/part-of: social-network
  template:
    metadata:
      labels:
        microless: social-network
        app.kubernetes.io/name: restful-gateway
        app.kubernetes.io/instance: k8s-deploy
        app.kubernetes.io/component: restful-gateway-vm
        app.kubernetes.io/part-of: social-network
      name: restful-gateway
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-gateway:0.1.7
        ports:
        - name: http
          containerPort: 8081
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json