# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/data.proto\x12\x1amicroless.hotelreservation\"\xd0\x01\n\x05Hotel\x12\x10\n\x08hotel_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x34\n\x07\x61\x64\x64ress\x18\x05 \x01(\x0b\x32#.microless.hotelreservation.Address\x12\x31\n\x06images\x18\x06 \x03(\x0b\x32!.microless.hotelreservation.Image\x12\x13\n\x0broom_number\x18\x07 \x01(\x05\"\x92\x01\n\x07\x41\x64\x64ress\x12\x15\n\rstreet_number\x18\x01 \x01(\t\x12\x13\n\x0bstreet_name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x13\n\x0bpostal_code\x18\x06 \x01(\t\x12\x0b\n\x03lat\x18\x07 \x01(\x01\x12\x0b\n\x03lon\x18\x08 \x01(\x01\"%\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x02 \x01(\x08\x42\"Z microless/hotelreservation/protob\x06proto3')



_HOTEL = DESCRIPTOR.message_types_by_name['Hotel']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Hotel = _reflection.GeneratedProtocolMessageType('Hotel', (_message.Message,), {
  'DESCRIPTOR' : _HOTEL,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.Hotel)
  })
_sym_db.RegisterMessage(Hotel)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.Address)
  })
_sym_db.RegisterMessage(Address)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.Image)
  })
_sym_db.RegisterMessage(Image)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z microless/hotelreservation/proto'
  _HOTEL._serialized_start=49
  _HOTEL._serialized_end=257
  _ADDRESS._serialized_start=260
  _ADDRESS._serialized_end=406
  _IMAGE._serialized_start=408
  _IMAGE._serialized_end=445
# @@protoc_insertion_point(module_scope)
