# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import geo_pb2 as proto_dot_geo__pb2


class GeoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Nearby = channel.unary_unary(
                '/microless.hotelreservation.geo.GeoService/Nearby',
                request_serializer=proto_dot_geo__pb2.NearbyRequest.SerializeToString,
                response_deserializer=proto_dot_geo__pb2.NearbyRespond.FromString,
                )
        self.AddHotel = channel.unary_unary(
                '/microless.hotelreservation.geo.GeoService/AddHotel',
                request_serializer=proto_dot_geo__pb2.AddHotelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class GeoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Nearby(self, request, context):
        """Finds the hotels contained nearby the current lat/lon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHotel(self, request, context):
        """Add a new hotel to the geospacial database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Nearby': grpc.unary_unary_rpc_method_handler(
                    servicer.Nearby,
                    request_deserializer=proto_dot_geo__pb2.NearbyRequest.FromString,
                    response_serializer=proto_dot_geo__pb2.NearbyRespond.SerializeToString,
            ),
            'AddHotel': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHotel,
                    request_deserializer=proto_dot_geo__pb2.AddHotelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.hotelreservation.geo.GeoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Nearby(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.hotelreservation.geo.GeoService/Nearby',
            proto_dot_geo__pb2.NearbyRequest.SerializeToString,
            proto_dot_geo__pb2.NearbyRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddHotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.hotelreservation.geo.GeoService/AddHotel',
            proto_dot_geo__pb2.AddHotelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
