# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import profile_pb2 as proto_dot_profile__pb2


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoomNumber = channel.unary_unary(
                '/microless.hotelreservation.profile.ProfileService/GetRoomNumber',
                request_serializer=proto_dot_profile__pb2.GetRoomNumberRequest.SerializeToString,
                response_deserializer=proto_dot_profile__pb2.GetRoomNumberRespond.FromString,
                )
        self.GetProfiles = channel.unary_unary(
                '/microless.hotelreservation.profile.ProfileService/GetProfiles',
                request_serializer=proto_dot_profile__pb2.GetProfilesRequest.SerializeToString,
                response_deserializer=proto_dot_profile__pb2.GetProfilesRespond.FromString,
                )
        self.AddProfile = channel.unary_unary(
                '/microless.hotelreservation.profile.ProfileService/AddProfile',
                request_serializer=proto_dot_profile__pb2.AddProfileRequest.SerializeToString,
                response_deserializer=proto_dot_profile__pb2.AddProfileRespond.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRoomNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoomNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomNumber,
                    request_deserializer=proto_dot_profile__pb2.GetRoomNumberRequest.FromString,
                    response_serializer=proto_dot_profile__pb2.GetRoomNumberRespond.SerializeToString,
            ),
            'GetProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfiles,
                    request_deserializer=proto_dot_profile__pb2.GetProfilesRequest.FromString,
                    response_serializer=proto_dot_profile__pb2.GetProfilesRespond.SerializeToString,
            ),
            'AddProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProfile,
                    request_deserializer=proto_dot_profile__pb2.AddProfileRequest.FromString,
                    response_serializer=proto_dot_profile__pb2.AddProfileRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.hotelreservation.profile.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRoomNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.hotelreservation.profile.ProfileService/GetRoomNumber',
            proto_dot_profile__pb2.GetRoomNumberRequest.SerializeToString,
            proto_dot_profile__pb2.GetRoomNumberRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.hotelreservation.profile.ProfileService/GetProfiles',
            proto_dot_profile__pb2.GetProfilesRequest.SerializeToString,
            proto_dot_profile__pb2.GetProfilesRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.hotelreservation.profile.ProfileService/AddProfile',
            proto_dot_profile__pb2.AddProfileRequest.SerializeToString,
            proto_dot_profile__pb2.AddProfileRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
