# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reservation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/reservation.proto\x12&microless.hotelreservation.reservation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xab\x01\n\x16MakeReservationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08hotel_id\x18\x02 \x01(\t\x12+\n\x07in_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08out_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0broom_number\x18\x05 \x01(\x05\"\x9d\x01\n\x18\x43heckAvailabilityRequest\x12\x11\n\thotel_ids\x18\x02 \x03(\t\x12+\n\x07in_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08out_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0broom_number\x18\x05 \x01(\x05\"-\n\x18\x43heckAvailabilityRespond\x12\x11\n\thotel_ids\x18\x01 \x03(\t2\xba\x02\n\x12ReservationService\x12\x89\x01\n\x0fMakeReservation\x12>.microless.hotelreservation.reservation.MakeReservationRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x13/api/v1/reservation:\x01*\x12\x97\x01\n\x11\x43heckAvailability\x12@.microless.hotelreservation.reservation.CheckAvailabilityRequest\x1a@.microless.hotelreservation.reservation.CheckAvailabilityRespondB.Z,microless/hotelreservation/proto/reservationb\x06proto3')



_MAKERESERVATIONREQUEST = DESCRIPTOR.message_types_by_name['MakeReservationRequest']
_CHECKAVAILABILITYREQUEST = DESCRIPTOR.message_types_by_name['CheckAvailabilityRequest']
_CHECKAVAILABILITYRESPOND = DESCRIPTOR.message_types_by_name['CheckAvailabilityRespond']
MakeReservationRequest = _reflection.GeneratedProtocolMessageType('MakeReservationRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAKERESERVATIONREQUEST,
  '__module__' : 'proto.reservation_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.reservation.MakeReservationRequest)
  })
_sym_db.RegisterMessage(MakeReservationRequest)

CheckAvailabilityRequest = _reflection.GeneratedProtocolMessageType('CheckAvailabilityRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKAVAILABILITYREQUEST,
  '__module__' : 'proto.reservation_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.reservation.CheckAvailabilityRequest)
  })
_sym_db.RegisterMessage(CheckAvailabilityRequest)

CheckAvailabilityRespond = _reflection.GeneratedProtocolMessageType('CheckAvailabilityRespond', (_message.Message,), {
  'DESCRIPTOR' : _CHECKAVAILABILITYRESPOND,
  '__module__' : 'proto.reservation_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.reservation.CheckAvailabilityRespond)
  })
_sym_db.RegisterMessage(CheckAvailabilityRespond)

_RESERVATIONSERVICE = DESCRIPTOR.services_by_name['ReservationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,microless/hotelreservation/proto/reservation'
  _RESERVATIONSERVICE.methods_by_name['MakeReservation']._options = None
  _RESERVATIONSERVICE.methods_by_name['MakeReservation']._serialized_options = b'\202\323\344\223\002\030\"\023/api/v1/reservation:\001*'
  _MAKERESERVATIONREQUEST._serialized_start=160
  _MAKERESERVATIONREQUEST._serialized_end=331
  _CHECKAVAILABILITYREQUEST._serialized_start=334
  _CHECKAVAILABILITYREQUEST._serialized_end=491
  _CHECKAVAILABILITYRESPOND._serialized_start=493
  _CHECKAVAILABILITYRESPOND._serialized_end=538
  _RESERVATIONSERVICE._serialized_start=541
  _RESERVATIONSERVICE._serialized_end=855
# @@protoc_insertion_point(module_scope)
