# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x1fmicroless.hotelreservation.user\x1a\x1cgoogle/api/annotations.proto\"9\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"&\n\x13RegisterUserRespond\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0cLoginRespond\x12\r\n\x05token\x18\x01 \x01(\t2\xb3\x02\n\x0bUserService\x12\x9c\x01\n\x0cRegisterUser\x12\x34.microless.hotelreservation.user.RegisterUserRequest\x1a\x34.microless.hotelreservation.user.RegisterUserRespond\" \x82\xd3\xe4\x93\x02\x1a\"\x15/api/v1/user/register:\x01*\x12\x84\x01\n\x05Login\x12-.microless.hotelreservation.user.LoginRequest\x1a-.microless.hotelreservation.user.LoginRespond\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/api/v1/user/login:\x01*B\'Z%microless/hotelreservation/proto/userb\x06proto3')



_REGISTERUSERREQUEST = DESCRIPTOR.message_types_by_name['RegisterUserRequest']
_REGISTERUSERRESPOND = DESCRIPTOR.message_types_by_name['RegisterUserRespond']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPOND = DESCRIPTOR.message_types_by_name['LoginRespond']
RegisterUserRequest = _reflection.GeneratedProtocolMessageType('RegisterUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERUSERREQUEST,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.user.RegisterUserRequest)
  })
_sym_db.RegisterMessage(RegisterUserRequest)

RegisterUserRespond = _reflection.GeneratedProtocolMessageType('RegisterUserRespond', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERUSERRESPOND,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.user.RegisterUserRespond)
  })
_sym_db.RegisterMessage(RegisterUserRespond)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.user.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginRespond = _reflection.GeneratedProtocolMessageType('LoginRespond', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPOND,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:microless.hotelreservation.user.LoginRespond)
  })
_sym_db.RegisterMessage(LoginRespond)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%microless/hotelreservation/proto/user'
  _USERSERVICE.methods_by_name['RegisterUser']._options = None
  _USERSERVICE.methods_by_name['RegisterUser']._serialized_options = b'\202\323\344\223\002\032\"\025/api/v1/user/register:\001*'
  _USERSERVICE.methods_by_name['Login']._options = None
  _USERSERVICE.methods_by_name['Login']._serialized_options = b'\202\323\344\223\002\027\"\022/api/v1/user/login:\001*'
  _REGISTERUSERREQUEST._serialized_start=83
  _REGISTERUSERREQUEST._serialized_end=140
  _REGISTERUSERRESPOND._serialized_start=142
  _REGISTERUSERRESPOND._serialized_end=180
  _LOGINREQUEST._serialized_start=182
  _LOGINREQUEST._serialized_end=232
  _LOGINRESPOND._serialized_start=234
  _LOGINRESPOND._serialized_end=263
  _USERSERVICE._serialized_start=266
  _USERSERVICE._serialized_end=573
# @@protoc_insertion_point(module_scope)
