// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/text.proto

package text

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	proto "microless/socialnetwork/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComposeTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ComposeTextRequest) Reset() {
	*x = ComposeTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeTextRequest) ProtoMessage() {}

func (x *ComposeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeTextRequest.ProtoReflect.Descriptor instead.
func (*ComposeTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_text_proto_rawDescGZIP(), []int{0}
}

func (x *ComposeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ComposeTextRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text        string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	UserMention []*proto.UserMention `protobuf:"bytes,2,rep,name=user_mention,json=userMention,proto3" json:"user_mention,omitempty"`
	Urls        []*proto.Url         `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ComposeTextRespond) Reset() {
	*x = ComposeTextRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_text_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeTextRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeTextRespond) ProtoMessage() {}

func (x *ComposeTextRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_text_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeTextRespond.ProtoReflect.Descriptor instead.
func (*ComposeTextRespond) Descriptor() ([]byte, []int) {
	return file_proto_text_proto_rawDescGZIP(), []int{1}
}

func (x *ComposeTextRespond) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ComposeTextRespond) GetUserMention() []*proto.UserMention {
	if x != nil {
		return x.UserMention
	}
	return nil
}

func (x *ComposeTextRespond) GetUrls() []*proto.Url {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_proto_text_proto protoreflect.FileDescriptor

var file_proto_text_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xa3, 0x01, 0x0a,
	0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x47, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x30, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x55, 0x72, 0x6c, 0x52, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x32, 0x80, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x71, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x30, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x74, 0x65,
	0x78, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x42, 0x24, 0x5a, 0x22, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x73, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_text_proto_rawDescOnce sync.Once
	file_proto_text_proto_rawDescData = file_proto_text_proto_rawDesc
)

func file_proto_text_proto_rawDescGZIP() []byte {
	file_proto_text_proto_rawDescOnce.Do(func() {
		file_proto_text_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_text_proto_rawDescData)
	})
	return file_proto_text_proto_rawDescData
}

var file_proto_text_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_text_proto_goTypes = []interface{}{
	(*ComposeTextRequest)(nil), // 0: microless.socialnetwork.text.ComposeTextRequest
	(*ComposeTextRespond)(nil), // 1: microless.socialnetwork.text.ComposeTextRespond
	(*proto.UserMention)(nil),  // 2: microless.socialnetwork.UserMention
	(*proto.Url)(nil),          // 3: microless.socialnetwork.Url
}
var file_proto_text_proto_depIdxs = []int32{
	2, // 0: microless.socialnetwork.text.ComposeTextRespond.user_mention:type_name -> microless.socialnetwork.UserMention
	3, // 1: microless.socialnetwork.text.ComposeTextRespond.urls:type_name -> microless.socialnetwork.Url
	0, // 2: microless.socialnetwork.text.TextService.ComposeText:input_type -> microless.socialnetwork.text.ComposeTextRequest
	1, // 3: microless.socialnetwork.text.TextService.ComposeText:output_type -> microless.socialnetwork.text.ComposeTextRespond
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_text_proto_init() }
func file_proto_text_proto_init() {
	if File_proto_text_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_text_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_text_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeTextRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_text_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_text_proto_goTypes,
		DependencyIndexes: file_proto_text_proto_depIdxs,
		MessageInfos:      file_proto_text_proto_msgTypes,
	}.Build()
	File_proto_text_proto = out.File
	file_proto_text_proto_rawDesc = nil
	file_proto_text_proto_goTypes = nil
	file_proto_text_proto_depIdxs = nil
}
