apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: pingpong
data:
  config.json: |
    {
      "service": {
        "ping": "ping:8080",
        "pong": "pong:8080"
      }
    }
  lb.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": false
      },
      "serverless": {
        "enable": false
      }
    }
