apiVersion: v1
kind: Service
metadata:
  name: post-storage
  labels:
    app: post-storage
    type: stats
  namespace: social-network
spec:
  clusterIP: None
  selector:
    app: post-storage
  ports:
  - name: stats
    port: 9000
    targetPort: stats
