# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bookings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/bookings.proto\x12\x1amicroless.acmeair.bookings\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x10proto/data.proto\"n\n\x12\x42ookFlightsRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x14\n\x0cto_flight_id\x18\x02 \x01(\t\x12\x15\n\rret_flight_id\x18\x04 \x01(\t\x12\x16\n\x0eone_way_flight\x18\x06 \x01(\x08\"E\n\x12\x42ookFlightsRespond\x12/\n\x07\x62ooking\x18\x01 \x01(\x0b\x32\x1e.microless.acmeair.BookingInfo\"+\n\x15GetBookingByIdRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\t\"H\n\x15GetBookingByIdRespond\x12/\n\x07\x62ooking\x18\x01 \x01(\x0b\x32\x1e.microless.acmeair.BookingInfo\".\n\x17GetBookingByUserRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"K\n\x17GetBookingByUserRespond\x12\x30\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x1e.microless.acmeair.BookingInfo\"C\n\x18\x43\x61ncelBookingByIdRequest\x12\x12\n\nbooking_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t2\x8c\x05\n\x0f\x42ookingsService\x12\x96\x01\n\x0b\x42ookFlights\x12..microless.acmeair.bookings.BookFlightsRequest\x1a..microless.acmeair.bookings.BookFlightsRespond\"\'\x82\xd3\xe4\x93\x02!\"\x1c/api/v1/bookings/bookflights:\x01*\x12\xa2\x01\n\x0eGetBookingById\x12\x31.microless.acmeair.bookings.GetBookingByIdRequest\x1a\x31.microless.acmeair.bookings.GetBookingByIdRespond\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/bookings/byid/{booking_id}\x12\xab\x01\n\x10GetBookingByUser\x12\x33.microless.acmeair.bookings.GetBookingByUserRequest\x1a\x33.microless.acmeair.bookings.GetBookingByUserRespond\"-\x82\xd3\xe4\x93\x02\'\x12%/api/v1/bookings/byuser/{customer_id}\x12\x8c\x01\n\x11\x43\x61ncelBookingById\x12\x34.microless.acmeair.bookings.CancelBookingByIdRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#\"\x1e/api/v1/bookings/cancelbooking:\x01*B\"Z microless/acmeair/proto/bookingsb\x06proto3')



_BOOKFLIGHTSREQUEST = DESCRIPTOR.message_types_by_name['BookFlightsRequest']
_BOOKFLIGHTSRESPOND = DESCRIPTOR.message_types_by_name['BookFlightsRespond']
_GETBOOKINGBYIDREQUEST = DESCRIPTOR.message_types_by_name['GetBookingByIdRequest']
_GETBOOKINGBYIDRESPOND = DESCRIPTOR.message_types_by_name['GetBookingByIdRespond']
_GETBOOKINGBYUSERREQUEST = DESCRIPTOR.message_types_by_name['GetBookingByUserRequest']
_GETBOOKINGBYUSERRESPOND = DESCRIPTOR.message_types_by_name['GetBookingByUserRespond']
_CANCELBOOKINGBYIDREQUEST = DESCRIPTOR.message_types_by_name['CancelBookingByIdRequest']
BookFlightsRequest = _reflection.GeneratedProtocolMessageType('BookFlightsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOOKFLIGHTSREQUEST,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.BookFlightsRequest)
  })
_sym_db.RegisterMessage(BookFlightsRequest)

BookFlightsRespond = _reflection.GeneratedProtocolMessageType('BookFlightsRespond', (_message.Message,), {
  'DESCRIPTOR' : _BOOKFLIGHTSRESPOND,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.BookFlightsRespond)
  })
_sym_db.RegisterMessage(BookFlightsRespond)

GetBookingByIdRequest = _reflection.GeneratedProtocolMessageType('GetBookingByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINGBYIDREQUEST,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.GetBookingByIdRequest)
  })
_sym_db.RegisterMessage(GetBookingByIdRequest)

GetBookingByIdRespond = _reflection.GeneratedProtocolMessageType('GetBookingByIdRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINGBYIDRESPOND,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.GetBookingByIdRespond)
  })
_sym_db.RegisterMessage(GetBookingByIdRespond)

GetBookingByUserRequest = _reflection.GeneratedProtocolMessageType('GetBookingByUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINGBYUSERREQUEST,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.GetBookingByUserRequest)
  })
_sym_db.RegisterMessage(GetBookingByUserRequest)

GetBookingByUserRespond = _reflection.GeneratedProtocolMessageType('GetBookingByUserRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINGBYUSERRESPOND,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.GetBookingByUserRespond)
  })
_sym_db.RegisterMessage(GetBookingByUserRespond)

CancelBookingByIdRequest = _reflection.GeneratedProtocolMessageType('CancelBookingByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANCELBOOKINGBYIDREQUEST,
  '__module__' : 'proto.bookings_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.bookings.CancelBookingByIdRequest)
  })
_sym_db.RegisterMessage(CancelBookingByIdRequest)

_BOOKINGSSERVICE = DESCRIPTOR.services_by_name['BookingsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z microless/acmeair/proto/bookings'
  _BOOKINGSSERVICE.methods_by_name['BookFlights']._options = None
  _BOOKINGSSERVICE.methods_by_name['BookFlights']._serialized_options = b'\202\323\344\223\002!\"\034/api/v1/bookings/bookflights:\001*'
  _BOOKINGSSERVICE.methods_by_name['GetBookingById']._options = None
  _BOOKINGSSERVICE.methods_by_name['GetBookingById']._serialized_options = b'\202\323\344\223\002$\022\"/api/v1/bookings/byid/{booking_id}'
  _BOOKINGSSERVICE.methods_by_name['GetBookingByUser']._options = None
  _BOOKINGSSERVICE.methods_by_name['GetBookingByUser']._serialized_options = b'\202\323\344\223\002\'\022%/api/v1/bookings/byuser/{customer_id}'
  _BOOKINGSSERVICE.methods_by_name['CancelBookingById']._options = None
  _BOOKINGSSERVICE.methods_by_name['CancelBookingById']._serialized_options = b'\202\323\344\223\002#\"\036/api/v1/bookings/cancelbooking:\001*'
  _BOOKFLIGHTSREQUEST._serialized_start=129
  _BOOKFLIGHTSREQUEST._serialized_end=239
  _BOOKFLIGHTSRESPOND._serialized_start=241
  _BOOKFLIGHTSRESPOND._serialized_end=310
  _GETBOOKINGBYIDREQUEST._serialized_start=312
  _GETBOOKINGBYIDREQUEST._serialized_end=355
  _GETBOOKINGBYIDRESPOND._serialized_start=357
  _GETBOOKINGBYIDRESPOND._serialized_end=429
  _GETBOOKINGBYUSERREQUEST._serialized_start=431
  _GETBOOKINGBYUSERREQUEST._serialized_end=477
  _GETBOOKINGBYUSERRESPOND._serialized_start=479
  _GETBOOKINGBYUSERRESPOND._serialized_end=554
  _CANCELBOOKINGBYIDREQUEST._serialized_start=556
  _CANCELBOOKINGBYIDREQUEST._serialized_end=623
  _BOOKINGSSERVICE._serialized_start=626
  _BOOKINGSSERVICE._serialized_end=1278
# @@protoc_insertion_point(module_scope)
