# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/customer.proto\x12\x1amicroless.acmeair.customer\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x10proto/data.proto\")\n\x12GetCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"G\n\x12GetCustomerRespond\x12\x31\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x1f.microless.acmeair.CustomerInfo\"\\\n\x12PutCustomerRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x31\n\x08\x63ustomer\x18\x02 \x01(\x0b\x32\x1f.microless.acmeair.CustomerInfo2\xb6\x02\n\x0f\x43ustomerService\x12\x9a\x01\n\x0bGetCustomer\x12..microless.acmeair.customer.GetCustomerRequest\x1a..microless.acmeair.customer.GetCustomerRespond\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/customer/byid/{customer_id}\x12\x85\x01\n\x0bPutCustomer\x12..microless.acmeair.customer.PutCustomerRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(\"#/api/v1/customer/byid/{customer_id}:\x01*B\"Z microless/acmeair/proto/customerb\x06proto3')



_GETCUSTOMERREQUEST = DESCRIPTOR.message_types_by_name['GetCustomerRequest']
_GETCUSTOMERRESPOND = DESCRIPTOR.message_types_by_name['GetCustomerRespond']
_PUTCUSTOMERREQUEST = DESCRIPTOR.message_types_by_name['PutCustomerRequest']
GetCustomerRequest = _reflection.GeneratedProtocolMessageType('GetCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERREQUEST,
  '__module__' : 'proto.customer_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.customer.GetCustomerRequest)
  })
_sym_db.RegisterMessage(GetCustomerRequest)

GetCustomerRespond = _reflection.GeneratedProtocolMessageType('GetCustomerRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERRESPOND,
  '__module__' : 'proto.customer_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.customer.GetCustomerRespond)
  })
_sym_db.RegisterMessage(GetCustomerRespond)

PutCustomerRequest = _reflection.GeneratedProtocolMessageType('PutCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTCUSTOMERREQUEST,
  '__module__' : 'proto.customer_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.customer.PutCustomerRequest)
  })
_sym_db.RegisterMessage(PutCustomerRequest)

_CUSTOMERSERVICE = DESCRIPTOR.services_by_name['CustomerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z microless/acmeair/proto/customer'
  _CUSTOMERSERVICE.methods_by_name['GetCustomer']._options = None
  _CUSTOMERSERVICE.methods_by_name['GetCustomer']._serialized_options = b'\202\323\344\223\002%\022#/api/v1/customer/byid/{customer_id}'
  _CUSTOMERSERVICE.methods_by_name['PutCustomer']._options = None
  _CUSTOMERSERVICE.methods_by_name['PutCustomer']._serialized_options = b'\202\323\344\223\002(\"#/api/v1/customer/byid/{customer_id}:\001*'
  _GETCUSTOMERREQUEST._serialized_start=129
  _GETCUSTOMERREQUEST._serialized_end=170
  _GETCUSTOMERRESPOND._serialized_start=172
  _GETCUSTOMERRESPOND._serialized_end=243
  _PUTCUSTOMERREQUEST._serialized_start=245
  _PUTCUSTOMERREQUEST._serialized_end=337
  _CUSTOMERSERVICE._serialized_start=340
  _CUSTOMERSERVICE._serialized_end=650
# @@protoc_insertion_point(module_scope)
