# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import customer_pb2 as proto_dot_customer__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCustomer = channel.unary_unary(
                '/microless.acmeair.customer.CustomerService/GetCustomer',
                request_serializer=proto_dot_customer__pb2.GetCustomerRequest.SerializeToString,
                response_deserializer=proto_dot_customer__pb2.GetCustomerRespond.FromString,
                )
        self.PutCustomer = channel.unary_unary(
                '/microless.acmeair.customer.CustomerService/PutCustomer',
                request_serializer=proto_dot_customer__pb2.PutCustomerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCustomer(self, request, context):
        """REST api
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomer,
                    request_deserializer=proto_dot_customer__pb2.GetCustomerRequest.FromString,
                    response_serializer=proto_dot_customer__pb2.GetCustomerRespond.SerializeToString,
            ),
            'PutCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCustomer,
                    request_deserializer=proto_dot_customer__pb2.PutCustomerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.acmeair.customer.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.acmeair.customer.CustomerService/GetCustomer',
            proto_dot_customer__pb2.GetCustomerRequest.SerializeToString,
            proto_dot_customer__pb2.GetCustomerRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.acmeair.customer.CustomerService/PutCustomer',
            proto_dot_customer__pb2.PutCustomerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
