# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/flights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/flights.proto\x12\x19microless.acmeair.flights\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x10proto/data.proto\"\xb9\x01\n\x15GetTripFlightsRequest\x12\x14\n\x0c\x66rom_airport\x18\x01 \x01(\t\x12\x12\n\nto_airport\x18\x02 \x01(\t\x12-\n\tfrom_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0breturn_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0eone_way_flight\x18\x05 \x01(\x08\"\x99\x01\n\x15GetTripFlightsRespond\x12\x31\n\nto_flights\x18\x01 \x03(\x0b\x32\x1d.microless.acmeair.FlightInfo\x12\x35\n\x0ereturn_flights\x18\x02 \x03(\x0b\x32\x1d.microless.acmeair.FlightInfo\x12\x16\n\x0eone_way_flight\x18\x03 \x01(\x08\"X\n\x14\x42rowseFlightsRequest\x12\x14\n\x0c\x66rom_airport\x18\x01 \x01(\t\x12\x12\n\nto_airport\x18\x02 \x01(\t\x12\x16\n\x0eone_way_flight\x18\x03 \x01(\x08\"\x98\x01\n\x14\x42rowseFlightsRespond\x12\x31\n\nto_flights\x18\x01 \x03(\x0b\x32\x1d.microless.acmeair.FlightInfo\x12\x35\n\x0ereturn_flights\x18\x02 \x03(\x0b\x32\x1d.microless.acmeair.FlightInfo\x12\x16\n\x0eone_way_flight\x18\x03 \x01(\x08\")\n\x14GetFlightByIdRequest\x12\x11\n\tflight_id\x18\x01 \x01(\t\"E\n\x14GetFlightByIdRespond\x12-\n\x06\x66light\x18\x01 \x01(\x0b\x32\x1d.microless.acmeair.FlightInfo2\xc1\x03\n\x0e\x46lightsService\x12\x9d\x01\n\x0eGetTripFlights\x12\x30.microless.acmeair.flights.GetTripFlightsRequest\x1a\x30.microless.acmeair.flights.GetTripFlightsRespond\"\'\x82\xd3\xe4\x93\x02!\"\x1c/api/v1/flights/queryflights:\x01*\x12\x9b\x01\n\rBrowseFlights\x12/.microless.acmeair.flights.BrowseFlightsRequest\x1a/.microless.acmeair.flights.BrowseFlightsRespond\"(\x82\xd3\xe4\x93\x02\"\"\x1d/api/v1/flights/browseflights:\x01*\x12q\n\rGetFlightById\x12/.microless.acmeair.flights.GetFlightByIdRequest\x1a/.microless.acmeair.flights.GetFlightByIdRespondB!Z\x1fmicroless/acmeair/proto/flightsb\x06proto3')



_GETTRIPFLIGHTSREQUEST = DESCRIPTOR.message_types_by_name['GetTripFlightsRequest']
_GETTRIPFLIGHTSRESPOND = DESCRIPTOR.message_types_by_name['GetTripFlightsRespond']
_BROWSEFLIGHTSREQUEST = DESCRIPTOR.message_types_by_name['BrowseFlightsRequest']
_BROWSEFLIGHTSRESPOND = DESCRIPTOR.message_types_by_name['BrowseFlightsRespond']
_GETFLIGHTBYIDREQUEST = DESCRIPTOR.message_types_by_name['GetFlightByIdRequest']
_GETFLIGHTBYIDRESPOND = DESCRIPTOR.message_types_by_name['GetFlightByIdRespond']
GetTripFlightsRequest = _reflection.GeneratedProtocolMessageType('GetTripFlightsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRIPFLIGHTSREQUEST,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.GetTripFlightsRequest)
  })
_sym_db.RegisterMessage(GetTripFlightsRequest)

GetTripFlightsRespond = _reflection.GeneratedProtocolMessageType('GetTripFlightsRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETTRIPFLIGHTSRESPOND,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.GetTripFlightsRespond)
  })
_sym_db.RegisterMessage(GetTripFlightsRespond)

BrowseFlightsRequest = _reflection.GeneratedProtocolMessageType('BrowseFlightsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROWSEFLIGHTSREQUEST,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.BrowseFlightsRequest)
  })
_sym_db.RegisterMessage(BrowseFlightsRequest)

BrowseFlightsRespond = _reflection.GeneratedProtocolMessageType('BrowseFlightsRespond', (_message.Message,), {
  'DESCRIPTOR' : _BROWSEFLIGHTSRESPOND,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.BrowseFlightsRespond)
  })
_sym_db.RegisterMessage(BrowseFlightsRespond)

GetFlightByIdRequest = _reflection.GeneratedProtocolMessageType('GetFlightByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFLIGHTBYIDREQUEST,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.GetFlightByIdRequest)
  })
_sym_db.RegisterMessage(GetFlightByIdRequest)

GetFlightByIdRespond = _reflection.GeneratedProtocolMessageType('GetFlightByIdRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETFLIGHTBYIDRESPOND,
  '__module__' : 'proto.flights_pb2'
  # @@protoc_insertion_point(class_scope:microless.acmeair.flights.GetFlightByIdRespond)
  })
_sym_db.RegisterMessage(GetFlightByIdRespond)

_FLIGHTSSERVICE = DESCRIPTOR.services_by_name['FlightsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037microless/acmeair/proto/flights'
  _FLIGHTSSERVICE.methods_by_name['GetTripFlights']._options = None
  _FLIGHTSSERVICE.methods_by_name['GetTripFlights']._serialized_options = b'\202\323\344\223\002!\"\034/api/v1/flights/queryflights:\001*'
  _FLIGHTSSERVICE.methods_by_name['BrowseFlights']._options = None
  _FLIGHTSSERVICE.methods_by_name['BrowseFlights']._serialized_options = b'\202\323\344\223\002\"\"\035/api/v1/flights/browseflights:\001*'
  _GETTRIPFLIGHTSREQUEST._serialized_start=132
  _GETTRIPFLIGHTSREQUEST._serialized_end=317
  _GETTRIPFLIGHTSRESPOND._serialized_start=320
  _GETTRIPFLIGHTSRESPOND._serialized_end=473
  _BROWSEFLIGHTSREQUEST._serialized_start=475
  _BROWSEFLIGHTSREQUEST._serialized_end=563
  _BROWSEFLIGHTSRESPOND._serialized_start=566
  _BROWSEFLIGHTSRESPOND._serialized_end=718
  _GETFLIGHTBYIDREQUEST._serialized_start=720
  _GETFLIGHTBYIDREQUEST._serialized_end=761
  _GETFLIGHTBYIDRESPOND._serialized_start=763
  _GETFLIGHTBYIDRESPOND._serialized_end=832
  _FLIGHTSSERVICE._serialized_start=835
  _FLIGHTSSERVICE._serialized_end=1284
# @@protoc_insertion_point(module_scope)
