# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import media_pb2 as proto_dot_media__pb2


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeMedia = channel.unary_unary(
                '/microless.socialnetwork.media.MediaService/ComposeMedia',
                request_serializer=proto_dot_media__pb2.ComposeMediaRequest.SerializeToString,
                response_deserializer=proto_dot_media__pb2.ComposeMediaRespond.FromString,
                )


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComposeMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeMedia,
                    request_deserializer=proto_dot_media__pb2.ComposeMediaRequest.FromString,
                    response_serializer=proto_dot_media__pb2.ComposeMediaRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.socialnetwork.media.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComposeMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.media.MediaService/ComposeMedia',
            proto_dot_media__pb2.ComposeMediaRequest.SerializeToString,
            proto_dot_media__pb2.ComposeMediaRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
