# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/media.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/media.proto\x12\x1dmicroless.socialnetwork.media\x1a\x10proto/data.proto\"=\n\x13\x43omposeMediaRequest\x12\x13\n\x0bmedia_types\x18\x01 \x03(\t\x12\x11\n\tmedia_ids\x18\x02 \x03(\x03\"D\n\x13\x43omposeMediaRespond\x12-\n\x05media\x18\x01 \x03(\x0b\x32\x1e.microless.socialnetwork.Media2\x86\x01\n\x0cMediaService\x12v\n\x0c\x43omposeMedia\x12\x32.microless.socialnetwork.media.ComposeMediaRequest\x1a\x32.microless.socialnetwork.media.ComposeMediaRespondB%Z#microless/socialnetwork/proto/mediab\x06proto3')



_COMPOSEMEDIAREQUEST = DESCRIPTOR.message_types_by_name['ComposeMediaRequest']
_COMPOSEMEDIARESPOND = DESCRIPTOR.message_types_by_name['ComposeMediaRespond']
ComposeMediaRequest = _reflection.GeneratedProtocolMessageType('ComposeMediaRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEMEDIAREQUEST,
  '__module__' : 'proto.media_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.media.ComposeMediaRequest)
  })
_sym_db.RegisterMessage(ComposeMediaRequest)

ComposeMediaRespond = _reflection.GeneratedProtocolMessageType('ComposeMediaRespond', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEMEDIARESPOND,
  '__module__' : 'proto.media_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.media.ComposeMediaRespond)
  })
_sym_db.RegisterMessage(ComposeMediaRespond)

_MEDIASERVICE = DESCRIPTOR.services_by_name['MediaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#microless/socialnetwork/proto/media'
  _COMPOSEMEDIAREQUEST._serialized_start=70
  _COMPOSEMEDIAREQUEST._serialized_end=131
  _COMPOSEMEDIARESPOND._serialized_start=133
  _COMPOSEMEDIARESPOND._serialized_end=201
  _MEDIASERVICE._serialized_start=204
  _MEDIASERVICE._serialized_end=338
# @@protoc_insertion_point(module_scope)
