# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/poststorage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/poststorage.proto\x12#microless.socialnetwork.poststorage\x1a\x10proto/data.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n\x10StorePostRequest\x12+\n\x04post\x18\x01 \x01(\x0b\x32\x1d.microless.socialnetwork.Post\"R\n\x10StorePostRespond\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"$\n\x10ReadPostsRequest\x12\x10\n\x08post_ids\x18\x01 \x03(\t\"@\n\x10ReadPostsRespond\x12,\n\x05posts\x18\x01 \x03(\x0b\x32\x1d.microless.socialnetwork.Post2\x8a\x02\n\x12PostStorageService\x12y\n\tStorePost\x12\x35.microless.socialnetwork.poststorage.StorePostRequest\x1a\x35.microless.socialnetwork.poststorage.StorePostRespond\x12y\n\tReadPosts\x12\x35.microless.socialnetwork.poststorage.ReadPostsRequest\x1a\x35.microless.socialnetwork.poststorage.ReadPostsRespondB+Z)microless/socialnetwork/proto/poststorageb\x06proto3')



_STOREPOSTREQUEST = DESCRIPTOR.message_types_by_name['StorePostRequest']
_STOREPOSTRESPOND = DESCRIPTOR.message_types_by_name['StorePostRespond']
_READPOSTSREQUEST = DESCRIPTOR.message_types_by_name['ReadPostsRequest']
_READPOSTSRESPOND = DESCRIPTOR.message_types_by_name['ReadPostsRespond']
StorePostRequest = _reflection.GeneratedProtocolMessageType('StorePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREPOSTREQUEST,
  '__module__' : 'proto.poststorage_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.poststorage.StorePostRequest)
  })
_sym_db.RegisterMessage(StorePostRequest)

StorePostRespond = _reflection.GeneratedProtocolMessageType('StorePostRespond', (_message.Message,), {
  'DESCRIPTOR' : _STOREPOSTRESPOND,
  '__module__' : 'proto.poststorage_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.poststorage.StorePostRespond)
  })
_sym_db.RegisterMessage(StorePostRespond)

ReadPostsRequest = _reflection.GeneratedProtocolMessageType('ReadPostsRequest', (_message.Message,), {
  'DESCRIPTOR' : _READPOSTSREQUEST,
  '__module__' : 'proto.poststorage_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.poststorage.ReadPostsRequest)
  })
_sym_db.RegisterMessage(ReadPostsRequest)

ReadPostsRespond = _reflection.GeneratedProtocolMessageType('ReadPostsRespond', (_message.Message,), {
  'DESCRIPTOR' : _READPOSTSRESPOND,
  '__module__' : 'proto.poststorage_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.poststorage.ReadPostsRespond)
  })
_sym_db.RegisterMessage(ReadPostsRespond)

_POSTSTORAGESERVICE = DESCRIPTOR.services_by_name['PostStorageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)microless/socialnetwork/proto/poststorage'
  _STOREPOSTREQUEST._serialized_start=115
  _STOREPOSTREQUEST._serialized_end=178
  _STOREPOSTRESPOND._serialized_start=180
  _STOREPOSTRESPOND._serialized_end=262
  _READPOSTSREQUEST._serialized_start=264
  _READPOSTSREQUEST._serialized_end=300
  _READPOSTSRESPOND._serialized_start=302
  _READPOSTSRESPOND._serialized_end=366
  _POSTSTORAGESERVICE._serialized_start=369
  _POSTSTORAGESERVICE._serialized_end=635
# @@protoc_insertion_point(module_scope)
