# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import poststorage_pb2 as proto_dot_poststorage__pb2


class PostStorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StorePost = channel.unary_unary(
                '/microless.socialnetwork.poststorage.PostStorageService/StorePost',
                request_serializer=proto_dot_poststorage__pb2.StorePostRequest.SerializeToString,
                response_deserializer=proto_dot_poststorage__pb2.StorePostRespond.FromString,
                )
        self.ReadPosts = channel.unary_unary(
                '/microless.socialnetwork.poststorage.PostStorageService/ReadPosts',
                request_serializer=proto_dot_poststorage__pb2.ReadPostsRequest.SerializeToString,
                response_deserializer=proto_dot_poststorage__pb2.ReadPostsRespond.FromString,
                )


class PostStorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StorePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StorePost': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePost,
                    request_deserializer=proto_dot_poststorage__pb2.StorePostRequest.FromString,
                    response_serializer=proto_dot_poststorage__pb2.StorePostRespond.SerializeToString,
            ),
            'ReadPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPosts,
                    request_deserializer=proto_dot_poststorage__pb2.ReadPostsRequest.FromString,
                    response_serializer=proto_dot_poststorage__pb2.ReadPostsRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.socialnetwork.poststorage.PostStorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostStorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StorePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.poststorage.PostStorageService/StorePost',
            proto_dot_poststorage__pb2.StorePostRequest.SerializeToString,
            proto_dot_poststorage__pb2.StorePostRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.poststorage.PostStorageService/ReadPosts',
            proto_dot_poststorage__pb2.ReadPostsRequest.SerializeToString,
            proto_dot_poststorage__pb2.ReadPostsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
