# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/text.proto\x12\x1cmicroless.socialnetwork.text\x1a\x10proto/data.proto\"\"\n\x12\x43omposeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x8a\x01\n\x12\x43omposeTextRespond\x12\x0c\n\x04text\x18\x01 \x01(\t\x12:\n\x0cuser_mention\x18\x02 \x03(\x0b\x32$.microless.socialnetwork.UserMention\x12*\n\x04urls\x18\x03 \x03(\x0b\x32\x1c.microless.socialnetwork.Url2\x80\x01\n\x0bTextService\x12q\n\x0b\x43omposeText\x12\x30.microless.socialnetwork.text.ComposeTextRequest\x1a\x30.microless.socialnetwork.text.ComposeTextRespondB$Z\"microless/socialnetwork/proto/textb\x06proto3')



_COMPOSETEXTREQUEST = DESCRIPTOR.message_types_by_name['ComposeTextRequest']
_COMPOSETEXTRESPOND = DESCRIPTOR.message_types_by_name['ComposeTextRespond']
ComposeTextRequest = _reflection.GeneratedProtocolMessageType('ComposeTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSETEXTREQUEST,
  '__module__' : 'proto.text_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.text.ComposeTextRequest)
  })
_sym_db.RegisterMessage(ComposeTextRequest)

ComposeTextRespond = _reflection.GeneratedProtocolMessageType('ComposeTextRespond', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSETEXTRESPOND,
  '__module__' : 'proto.text_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.text.ComposeTextRespond)
  })
_sym_db.RegisterMessage(ComposeTextRespond)

_TEXTSERVICE = DESCRIPTOR.services_by_name['TextService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\"microless/socialnetwork/proto/text'
  _COMPOSETEXTREQUEST._serialized_start=68
  _COMPOSETEXTREQUEST._serialized_end=102
  _COMPOSETEXTRESPOND._serialized_start=105
  _COMPOSETEXTRESPOND._serialized_end=243
  _TEXTSERVICE._serialized_start=246
  _TEXTSERVICE._serialized_end=374
# @@protoc_insertion_point(module_scope)
