# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import uniqueid_pb2 as proto_dot_uniqueid__pb2


class UniqueIdServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeUniqueId = channel.unary_unary(
                '/microless.socialnetwork.uniqueid.UniqueIdService/ComposeUniqueId',
                request_serializer=proto_dot_uniqueid__pb2.ComposeUniqueIdRequest.SerializeToString,
                response_deserializer=proto_dot_uniqueid__pb2.ComposeUniqueIdRespond.FromString,
                )


class UniqueIdServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComposeUniqueId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniqueIdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeUniqueId': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeUniqueId,
                    request_deserializer=proto_dot_uniqueid__pb2.ComposeUniqueIdRequest.FromString,
                    response_serializer=proto_dot_uniqueid__pb2.ComposeUniqueIdRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.socialnetwork.uniqueid.UniqueIdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UniqueIdService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComposeUniqueId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.uniqueid.UniqueIdService/ComposeUniqueId',
            proto_dot_uniqueid__pb2.ComposeUniqueIdRequest.SerializeToString,
            proto_dot_uniqueid__pb2.ComposeUniqueIdRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
