# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/urlshorten.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/urlshorten.proto\x12\"microless.socialnetwork.urlshorten\x1a\x10proto/data.proto\"\"\n\x12\x43omposeUrlsRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\"@\n\x12\x43omposeUrlsRespond\x12*\n\x04urls\x18\x02 \x03(\x0b\x32\x1c.microless.socialnetwork.Url\"0\n\x16GetExtendedUrlsRequest\x12\x16\n\x0eshortened_urls\x18\x01 \x03(\t\"&\n\x16GetExtendedUrlsRespond\x12\x0c\n\x04urls\x18\x02 \x03(\t2\x9e\x02\n\x11UrlShortenService\x12}\n\x0b\x43omposeUrls\x12\x36.microless.socialnetwork.urlshorten.ComposeUrlsRequest\x1a\x36.microless.socialnetwork.urlshorten.ComposeUrlsRespond\x12\x89\x01\n\x0fGetExtendedUrls\x12:.microless.socialnetwork.urlshorten.GetExtendedUrlsRequest\x1a:.microless.socialnetwork.urlshorten.GetExtendedUrlsRespondB*Z(microless/socialnetwork/proto/urlshortenb\x06proto3')



_COMPOSEURLSREQUEST = DESCRIPTOR.message_types_by_name['ComposeUrlsRequest']
_COMPOSEURLSRESPOND = DESCRIPTOR.message_types_by_name['ComposeUrlsRespond']
_GETEXTENDEDURLSREQUEST = DESCRIPTOR.message_types_by_name['GetExtendedUrlsRequest']
_GETEXTENDEDURLSRESPOND = DESCRIPTOR.message_types_by_name['GetExtendedUrlsRespond']
ComposeUrlsRequest = _reflection.GeneratedProtocolMessageType('ComposeUrlsRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEURLSREQUEST,
  '__module__' : 'proto.urlshorten_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.urlshorten.ComposeUrlsRequest)
  })
_sym_db.RegisterMessage(ComposeUrlsRequest)

ComposeUrlsRespond = _reflection.GeneratedProtocolMessageType('ComposeUrlsRespond', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEURLSRESPOND,
  '__module__' : 'proto.urlshorten_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.urlshorten.ComposeUrlsRespond)
  })
_sym_db.RegisterMessage(ComposeUrlsRespond)

GetExtendedUrlsRequest = _reflection.GeneratedProtocolMessageType('GetExtendedUrlsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEXTENDEDURLSREQUEST,
  '__module__' : 'proto.urlshorten_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.urlshorten.GetExtendedUrlsRequest)
  })
_sym_db.RegisterMessage(GetExtendedUrlsRequest)

GetExtendedUrlsRespond = _reflection.GeneratedProtocolMessageType('GetExtendedUrlsRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETEXTENDEDURLSRESPOND,
  '__module__' : 'proto.urlshorten_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.urlshorten.GetExtendedUrlsRespond)
  })
_sym_db.RegisterMessage(GetExtendedUrlsRespond)

_URLSHORTENSERVICE = DESCRIPTOR.services_by_name['UrlShortenService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(microless/socialnetwork/proto/urlshorten'
  _COMPOSEURLSREQUEST._serialized_start=80
  _COMPOSEURLSREQUEST._serialized_end=114
  _COMPOSEURLSRESPOND._serialized_start=116
  _COMPOSEURLSRESPOND._serialized_end=180
  _GETEXTENDEDURLSREQUEST._serialized_start=182
  _GETEXTENDEDURLSREQUEST._serialized_end=230
  _GETEXTENDEDURLSRESPOND._serialized_start=232
  _GETEXTENDEDURLSRESPOND._serialized_end=270
  _URLSHORTENSERVICE._serialized_start=273
  _URLSHORTENSERVICE._serialized_end=559
# @@protoc_insertion_point(module_scope)
