# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import urlshorten_pb2 as proto_dot_urlshorten__pb2


class UrlShortenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeUrls = channel.unary_unary(
                '/microless.socialnetwork.urlshorten.UrlShortenService/ComposeUrls',
                request_serializer=proto_dot_urlshorten__pb2.ComposeUrlsRequest.SerializeToString,
                response_deserializer=proto_dot_urlshorten__pb2.ComposeUrlsRespond.FromString,
                )
        self.GetExtendedUrls = channel.unary_unary(
                '/microless.socialnetwork.urlshorten.UrlShortenService/GetExtendedUrls',
                request_serializer=proto_dot_urlshorten__pb2.GetExtendedUrlsRequest.SerializeToString,
                response_deserializer=proto_dot_urlshorten__pb2.GetExtendedUrlsRespond.FromString,
                )


class UrlShortenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComposeUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtendedUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrlShortenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeUrls,
                    request_deserializer=proto_dot_urlshorten__pb2.ComposeUrlsRequest.FromString,
                    response_serializer=proto_dot_urlshorten__pb2.ComposeUrlsRespond.SerializeToString,
            ),
            'GetExtendedUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtendedUrls,
                    request_deserializer=proto_dot_urlshorten__pb2.GetExtendedUrlsRequest.FromString,
                    response_serializer=proto_dot_urlshorten__pb2.GetExtendedUrlsRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.socialnetwork.urlshorten.UrlShortenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UrlShortenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComposeUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.urlshorten.UrlShortenService/ComposeUrls',
            proto_dot_urlshorten__pb2.ComposeUrlsRequest.SerializeToString,
            proto_dot_urlshorten__pb2.ComposeUrlsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExtendedUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.urlshorten.UrlShortenService/GetExtendedUrls',
            proto_dot_urlshorten__pb2.GetExtendedUrlsRequest.SerializeToString,
            proto_dot_urlshorten__pb2.GetExtendedUrlsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
