# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/usermention.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import data_pb2 as proto_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/usermention.proto\x12#microless.socialnetwork.usermention\x1a\x10proto/data.proto\"/\n\x1a\x43omposeUserMentionsRequest\x12\x11\n\tusernames\x18\x01 \x03(\t\"Y\n\x1a\x43omposeUserMentionsRespond\x12;\n\ruser_mentions\x18\x01 \x03(\x0b\x32$.microless.socialnetwork.UserMention2\xae\x01\n\x12UserMentionService\x12\x97\x01\n\x13\x43omposeUserMentions\x12?.microless.socialnetwork.usermention.ComposeUserMentionsRequest\x1a?.microless.socialnetwork.usermention.ComposeUserMentionsRespondB+Z)microless/socialnetwork/proto/usermentionb\x06proto3')



_COMPOSEUSERMENTIONSREQUEST = DESCRIPTOR.message_types_by_name['ComposeUserMentionsRequest']
_COMPOSEUSERMENTIONSRESPOND = DESCRIPTOR.message_types_by_name['ComposeUserMentionsRespond']
ComposeUserMentionsRequest = _reflection.GeneratedProtocolMessageType('ComposeUserMentionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEUSERMENTIONSREQUEST,
  '__module__' : 'proto.usermention_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.usermention.ComposeUserMentionsRequest)
  })
_sym_db.RegisterMessage(ComposeUserMentionsRequest)

ComposeUserMentionsRespond = _reflection.GeneratedProtocolMessageType('ComposeUserMentionsRespond', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSEUSERMENTIONSRESPOND,
  '__module__' : 'proto.usermention_pb2'
  # @@protoc_insertion_point(class_scope:microless.socialnetwork.usermention.ComposeUserMentionsRespond)
  })
_sym_db.RegisterMessage(ComposeUserMentionsRespond)

_USERMENTIONSERVICE = DESCRIPTOR.services_by_name['UserMentionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)microless/socialnetwork/proto/usermention'
  _COMPOSEUSERMENTIONSREQUEST._serialized_start=82
  _COMPOSEUSERMENTIONSREQUEST._serialized_end=129
  _COMPOSEUSERMENTIONSRESPOND._serialized_start=131
  _COMPOSEUSERMENTIONSRESPOND._serialized_end=220
  _USERMENTIONSERVICE._serialized_start=223
  _USERMENTIONSERVICE._serialized_end=397
# @@protoc_insertion_point(module_scope)
