# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import usermention_pb2 as proto_dot_usermention__pb2


class UserMentionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeUserMentions = channel.unary_unary(
                '/microless.socialnetwork.usermention.UserMentionService/ComposeUserMentions',
                request_serializer=proto_dot_usermention__pb2.ComposeUserMentionsRequest.SerializeToString,
                response_deserializer=proto_dot_usermention__pb2.ComposeUserMentionsRespond.FromString,
                )


class UserMentionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComposeUserMentions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserMentionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeUserMentions': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeUserMentions,
                    request_deserializer=proto_dot_usermention__pb2.ComposeUserMentionsRequest.FromString,
                    response_serializer=proto_dot_usermention__pb2.ComposeUserMentionsRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microless.socialnetwork.usermention.UserMentionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserMentionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComposeUserMentions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microless.socialnetwork.usermention.UserMentionService/ComposeUserMentions',
            proto_dot_usermention__pb2.ComposeUserMentionsRequest.SerializeToString,
            proto_dot_usermention__pb2.ComposeUserMentionsRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
