apiVersion: v1
kind: Namespace
metadata:
  name: video-kn-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
  namespace: video-kn-test
data:
  config.json: |
    {
      "rest": ":8080",
      "minio": {
          "url": "minio.minio:9000",
          "access_key": "minioadmin",
          "secret_key": "minioadmin",
          "secure": false
      },
      "service": {
          "video": "http://video.video-kn.svc.cluster.local:80/",
          "preview": "http://preview.video-kn.svc.cluster.local:80/",
          "split": "http://split.video-kn.svc.cluster.local:80/",
          "transcode": "http://transcode.video-kn.svc.cluster.local:80/",
          "merge": "http://merge.video-kn.svc.cluster.local:80/"
      }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: video-kn-test
spec:
  template:
    spec:
      containers:
      - name: test
        image: waterlemongan/microless-video-test:0.1.0
        env:
        - name: TEST_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config-test
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config-test
          configMap:
            name: config-test
            items:
            - key: config.json
              path: config.json
      restartPolicy: Never
  backoffLimit: 0