// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: proto/urlshorten.proto

package urlshorten

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlShortenServiceClient is the client API for UrlShortenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlShortenServiceClient interface {
	ComposeUrls(ctx context.Context, in *ComposeUrlsRequest, opts ...grpc.CallOption) (*ComposeUrlsRespond, error)
	GetExtendedUrls(ctx context.Context, in *GetExtendedUrlsRequest, opts ...grpc.CallOption) (*GetExtendedUrlsRespond, error)
}

type urlShortenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShortenServiceClient(cc grpc.ClientConnInterface) UrlShortenServiceClient {
	return &urlShortenServiceClient{cc}
}

func (c *urlShortenServiceClient) ComposeUrls(ctx context.Context, in *ComposeUrlsRequest, opts ...grpc.CallOption) (*ComposeUrlsRespond, error) {
	out := new(ComposeUrlsRespond)
	err := c.cc.Invoke(ctx, "/microless.socialnetwork.urlshorten.UrlShortenService/ComposeUrls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortenServiceClient) GetExtendedUrls(ctx context.Context, in *GetExtendedUrlsRequest, opts ...grpc.CallOption) (*GetExtendedUrlsRespond, error) {
	out := new(GetExtendedUrlsRespond)
	err := c.cc.Invoke(ctx, "/microless.socialnetwork.urlshorten.UrlShortenService/GetExtendedUrls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortenServiceServer is the server API for UrlShortenService service.
// All implementations must embed UnimplementedUrlShortenServiceServer
// for forward compatibility
type UrlShortenServiceServer interface {
	ComposeUrls(context.Context, *ComposeUrlsRequest) (*ComposeUrlsRespond, error)
	GetExtendedUrls(context.Context, *GetExtendedUrlsRequest) (*GetExtendedUrlsRespond, error)
	mustEmbedUnimplementedUrlShortenServiceServer()
}

// UnimplementedUrlShortenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUrlShortenServiceServer struct {
}

func (UnimplementedUrlShortenServiceServer) ComposeUrls(context.Context, *ComposeUrlsRequest) (*ComposeUrlsRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComposeUrls not implemented")
}
func (UnimplementedUrlShortenServiceServer) GetExtendedUrls(context.Context, *GetExtendedUrlsRequest) (*GetExtendedUrlsRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtendedUrls not implemented")
}
func (UnimplementedUrlShortenServiceServer) mustEmbedUnimplementedUrlShortenServiceServer() {}

// UnsafeUrlShortenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlShortenServiceServer will
// result in compilation errors.
type UnsafeUrlShortenServiceServer interface {
	mustEmbedUnimplementedUrlShortenServiceServer()
}

func RegisterUrlShortenServiceServer(s grpc.ServiceRegistrar, srv UrlShortenServiceServer) {
	s.RegisterService(&UrlShortenService_ServiceDesc, srv)
}

func _UrlShortenService_ComposeUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposeUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenServiceServer).ComposeUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microless.socialnetwork.urlshorten.UrlShortenService/ComposeUrls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenServiceServer).ComposeUrls(ctx, req.(*ComposeUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortenService_GetExtendedUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtendedUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenServiceServer).GetExtendedUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microless.socialnetwork.urlshorten.UrlShortenService/GetExtendedUrls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenServiceServer).GetExtendedUrls(ctx, req.(*GetExtendedUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlShortenService_ServiceDesc is the grpc.ServiceDesc for UrlShortenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlShortenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microless.socialnetwork.urlshorten.UrlShortenService",
	HandlerType: (*UrlShortenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComposeUrls",
			Handler:    _UrlShortenService_ComposeUrls_Handler,
		},
		{
			MethodName: "GetExtendedUrls",
			Handler:    _UrlShortenService_GetExtendedUrls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/urlshorten.proto",
}
