apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: split
  labels:
    microless: video
    app.kubernetes.io/name: split
    app.kubernetes.io/instance: kn-deploy
    app.kubernetes.io/component: split-service
    app.kubernetes.io/part-of: video
    networking.knative.dev/visibility: cluster-local
  namespace: video-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-video-split:0.1.0
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json