apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: social-network
data:
  config.json: |
    {
      "otel": "otel-collector-service.arms-prom:4317",
      "mongodb": {
        "url": "mongodb://172.17.0.10:27017",
        "database": "social-network"
      },
      "redis": {
        "usertimeline": "redis://172.17.0.10:6379/0",
        "socialgraph": "redis://172.17.0.10:6379/1",
        "hometimeline": "redis://172.17.0.10:6379/2",
        "poststorage": "redis://172.17.0.10:6379/3",
        "user": "redis://172.17.0.10:6379/4",
        "urlshorten": "redis://172.17.0.10:6379/5"
      },
      "service": {
        "poststorage": "post-storage:8080",
        "usertimeline": "user-timeline:8080",
        "user": "user:8080",
        "socialgraph": "social-graph:8080",
        "hometimeline": "home-timeline:8080",
        "media": "media:8080",
        "urlshorten": "url-shorten:8080",
        "usermention": "user-mention:8080",
        "text": "text:8080",
        "composepost": "compose-post:8080"
      },
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }
  lb.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": false
      },
      "serverless": {
        "enable": false
      }
    }