apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: compose-post
  labels:
    microless: social-network
    app.kubernetes.io/name: compose-post
    app.kubernetes.io/instance: kn-deploy
    app.kubernetes.io/component: compose-post-service
    app.kubernetes.io/part-of: social-network
    networking.knative.dev/visibility: cluster-local
  namespace: social-network-kn
spec:
  template:
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-composepost:0.1.4
        ports:
        - name: h2c
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json