apiVersion: v1
kind: Service
metadata:
  name: pong
  labels:
    app: pong
    type: stats
  namespace: pingpong
spec:
  clusterIP: None
  selector:
    app: pong
  ports:
  - name: stats
    port: 9000
    targetPort: stats
