version: '3'

volumes:
  minio-data:
  jaeger-data:

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - SPAN_STORAGE_TYPE=badger
    command:
      - --collector.otlp.enabled=true
      - --badger.ephemeral=true
      - --badger.directory-key=/badger/keys
      - --badger.directory-value=/badger/values
    volumes:
      - jaeger-data:/badger

  minio:
    image: quay.io/minio/minio:RELEASE.2022-10-15T19-57-03Z
    restart: always
    volumes:
      - minio-data:/data
    command: ["server", "/data"]

  mapreduce:
    image: waterlemongan/microless-mapreduce-mapreduce:0.1.0
    volumes:
      - ./config.json:/config.json:ro
    depends_on:
      - file
      - mapper
      - reducer

  file:
    image: waterlemongan/microless-mapreduce-file:0.1.0
    volumes:
      - ./config.json:/config.json:ro
    depends_on:
      - minio

  mapper:
    image: waterlemongan/microless-mapreduce-mapper:0.1.0
    volumes:
      - ./config.json:/config.json:ro
    depends_on:
      - minio

  reducer:
    image: waterlemongan/microless-mapreduce-reducer:0.1.0
    volumes:
      - ./config.json:/config.json:ro