apiVersion: v1
kind: Service
metadata:
  name: user-mention
  labels:
    app: user-mention
    type: stats
  namespace: social-network
spec:
  clusterIP: None
  selector:
    app: user-mention
  ports:
  - name: stats
    port: 9000
    targetPort: stats
