apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: social-network
data:
  config.json: |
    {
      "otel": "otel-collector-service.arms-prom:4317",
      "mongodb": {
        "url": "mongodb://172.17.0.10:27017",
        "database": "social-network"
      },
      "redis": {
        "usertimeline": "redis://172.17.0.10:6379/0",
        "socialgraph": "redis://172.17.0.10:6379/1",
        "hometimeline": "redis://172.17.0.10:6379/2",
        "poststorage": "redis://172.17.0.10:6379/3",
        "user": "redis://172.17.0.10:6379/4",
        "urlshorten": "redis://172.17.0.10:6379/5"
      },
      "service": {
        "poststorage": "post-storage:8080",
        "usertimeline": "user-timeline:8080",
        "user": "user:8080",
        "socialgraph": "social-graph:8080",
        "hometimeline": "home-timeline:8080",
        "media": "media:8080",
        "urlshorten": "url-shorten:8080",
        "usermention": "user-mention:8080",
        "text": "text:8080",
        "composepost": "compose-post:8080"
      },
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }
  lb.json: |
    {
      "server": {
        "enable": true,
        "update_interval": 1,
        "update_ratio": 0.5
      },
      "client": {
        "enable": true,
        "vm_postfix": "-vm",
        "serverless_postfix": "-serverless",
        "update_interval": 1,
        "retry": 1,
        "service_rate_limit": {
          "post-storage": 900,
          "user-timeline": 600,
          "user": 100,
          "social-graph": 100,
          "home-timeline": 600,
          "media": 100,
          "url-shorten": 100,
          "user-mention": 100,
          "text": 100,
          "compose-post": 100
        },
        "local_services": {},
        "redis_addr": "redis://172.17.0.10:6379/7"
      },
      "serverless": {
        "enable": false
      }
    }
  lb-gateway.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": true,
        "vm_postfix": "-vm",
        "serverless_postfix": "-serverless",
        "update_interval": 1,
        "retry": 1,
        "service_rate_limit": {
          "post-storage": 900,
          "user-timeline": 600,
          "user": 100,
          "social-graph": 100,
          "home-timeline": 600,
          "media": 100,
          "url-shorten": 100,
          "user-mention": 100,
          "text": 100,
          "compose-post": 100
        },
        "local_services": {},
        "redis_addr": "redis://172.17.0.10:6379/7"
      },
      "serverless": {
        "enable": false
      }
    }
