apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
  name: gateway
  namespace: pingpong
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 8080
    targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: pingpong
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      name: gateway
      namespace: pingpong
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-pingpong-gateway:0.1.1
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        - name: SERVICE_ADDR
          value: ":8080"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
            - key: lb.json
              path: lb.json
