// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/reviewstorage.proto

package reviewstorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	proto "microless/media/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreReviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId string `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Text    string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Rating  int32  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *StoreReviewRequest) Reset() {
	*x = StoreReviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reviewstorage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReviewRequest) ProtoMessage() {}

func (x *StoreReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviewstorage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReviewRequest.ProtoReflect.Descriptor instead.
func (*StoreReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_reviewstorage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreReviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreReviewRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *StoreReviewRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StoreReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type StoreReviewRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewId  string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *StoreReviewRespond) Reset() {
	*x = StoreReviewRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reviewstorage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreReviewRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReviewRespond) ProtoMessage() {}

func (x *StoreReviewRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviewstorage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReviewRespond.ProtoReflect.Descriptor instead.
func (*StoreReviewRespond) Descriptor() ([]byte, []int) {
	return file_proto_reviewstorage_proto_rawDescGZIP(), []int{1}
}

func (x *StoreReviewRespond) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *StoreReviewRespond) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReadReviewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReviewIds []string `protobuf:"bytes,1,rep,name=review_ids,json=reviewIds,proto3" json:"review_ids,omitempty"`
}

func (x *ReadReviewsRequest) Reset() {
	*x = ReadReviewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reviewstorage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReviewsRequest) ProtoMessage() {}

func (x *ReadReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviewstorage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReviewsRequest.ProtoReflect.Descriptor instead.
func (*ReadReviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_reviewstorage_proto_rawDescGZIP(), []int{2}
}

func (x *ReadReviewsRequest) GetReviewIds() []string {
	if x != nil {
		return x.ReviewIds
	}
	return nil
}

type ReadReviewsRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reviews []*proto.Review `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
}

func (x *ReadReviewsRespond) Reset() {
	*x = ReadReviewsRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reviewstorage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadReviewsRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReviewsRespond) ProtoMessage() {}

func (x *ReadReviewsRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reviewstorage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReviewsRespond.ProtoReflect.Descriptor instead.
func (*ReadReviewsRespond) Descriptor() ([]byte, []int) {
	return file_proto_reviewstorage_proto_rawDescGZIP(), []int{3}
}

func (x *ReadReviewsRespond) GetReviews() []*proto.Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_proto_reviewstorage_proto protoreflect.FileDescriptor

var file_proto_reviewstorage_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x22, 0x6b, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x33, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x49, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x32, 0x80,
	0x02, 0x0a, 0x14, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x31, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x73, 0x0a, 0x0b,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x31, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x64, 0x42, 0x25, 0x5a, 0x23, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x73, 0x2f, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reviewstorage_proto_rawDescOnce sync.Once
	file_proto_reviewstorage_proto_rawDescData = file_proto_reviewstorage_proto_rawDesc
)

func file_proto_reviewstorage_proto_rawDescGZIP() []byte {
	file_proto_reviewstorage_proto_rawDescOnce.Do(func() {
		file_proto_reviewstorage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reviewstorage_proto_rawDescData)
	})
	return file_proto_reviewstorage_proto_rawDescData
}

var file_proto_reviewstorage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_reviewstorage_proto_goTypes = []interface{}{
	(*StoreReviewRequest)(nil),    // 0: microless.media.reviewstorage.StoreReviewRequest
	(*StoreReviewRespond)(nil),    // 1: microless.media.reviewstorage.StoreReviewRespond
	(*ReadReviewsRequest)(nil),    // 2: microless.media.reviewstorage.ReadReviewsRequest
	(*ReadReviewsRespond)(nil),    // 3: microless.media.reviewstorage.ReadReviewsRespond
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*proto.Review)(nil),          // 5: microless.media.Review
}
var file_proto_reviewstorage_proto_depIdxs = []int32{
	4, // 0: microless.media.reviewstorage.StoreReviewRespond.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: microless.media.reviewstorage.ReadReviewsRespond.reviews:type_name -> microless.media.Review
	0, // 2: microless.media.reviewstorage.ReviewStorageService.StoreReview:input_type -> microless.media.reviewstorage.StoreReviewRequest
	2, // 3: microless.media.reviewstorage.ReviewStorageService.ReadReviews:input_type -> microless.media.reviewstorage.ReadReviewsRequest
	1, // 4: microless.media.reviewstorage.ReviewStorageService.StoreReview:output_type -> microless.media.reviewstorage.StoreReviewRespond
	3, // 5: microless.media.reviewstorage.ReviewStorageService.ReadReviews:output_type -> microless.media.reviewstorage.ReadReviewsRespond
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_reviewstorage_proto_init() }
func file_proto_reviewstorage_proto_init() {
	if File_proto_reviewstorage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reviewstorage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreReviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reviewstorage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreReviewRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reviewstorage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReviewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reviewstorage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadReviewsRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reviewstorage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reviewstorage_proto_goTypes,
		DependencyIndexes: file_proto_reviewstorage_proto_depIdxs,
		MessageInfos:      file_proto_reviewstorage_proto_msgTypes,
	}.Build()
	File_proto_reviewstorage_proto = out.File
	file_proto_reviewstorage_proto_rawDesc = nil
	file_proto_reviewstorage_proto_goTypes = nil
	file_proto_reviewstorage_proto_depIdxs = nil
}
