apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: social-network
data:
  config.json: |
    {
      "otel": "otel-collector-service.arms-prom:4317",
      "mongodb": {
        "url": "mongodb://172.17.0.10:27017",
        "database": "social-network"
      },
      "redis": {
        "usertimeline": "redis://172.17.0.10:6379/0",
        "socialgraph": "redis://172.17.0.10:6379/1",
        "hometimeline": "redis://172.17.0.10:6379/2",
        "poststorage": "redis://172.17.0.10:6379/3",
        "user": "redis://172.17.0.10:6379/4",
        "urlshorten": "redis://172.17.0.10:6379/5"
      },
      "service": {
        "poststorage": "post-storage.social-network.svc.cluster.local:80",
        "usertimeline": "user-timeline.social-network.svc.cluster.local:80",
        "user": "user.social-network.svc.cluster.local:80",
        "socialgraph": "social-graph.social-network.svc.cluster.local:80",
        "hometimeline": "home-timeline.social-network.svc.cluster.local:80",
        "media": "media.social-network.svc.cluster.local:80",
        "urlshorten": "url-shorten.social-network.svc.cluster.local:80",
        "usermention": "user-mention.social-network.svc.cluster.local:80",
        "text": "text.social-network.svc.cluster.local:80",
        "composepost": "compose-post.social-network.svc.cluster.local:80"
      },
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }
  lb.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": false
      },
      "serverless": {
        "enable": false
      }
    }