apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
  name: gateway
  namespace: social-network
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  type: LoadBalancer
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: social-network
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "1"
        sidecar.istio.io/proxyCPULimit: "2"
        sidecar.istio.io/proxyMemory: 200Mi
        sidecar.istio.io/proxyMemoryLimit: 1Gi
      labels:
        app: gateway
        sidecar.istio.io/inject: "true"
      name: gateway
      namespace: social-network
    spec:
      nodeSelector:
        type: system
      containers:
      - name: server
        image: waterlemongan/microless-socialnetwork-gateway:0.3.2
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        - name: SERVICE_ADDR
          value: ":8080"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 100Mi
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.json
            path: config.json
          - key: lb.json
            path: lb.json
