apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: media
data:
  config.json: |
    {
      "otel": "jaeger.jaeger:4317",
      "mongodb": {
        "url": "mongodb://mongodb.mongodb:27017",
        "database": "media"
      },
      "redis": {
        "moviereview": "redis://redis.redis:6379/0",
        "userreview": "redis://redis.redis:6379/1",
        "castinfo": "redis://redis.redis:6379/2",
        "movieinfo": "redis://redis.redis:6379/3",
        "plot": "redis://redis.redis:6379/4",
        "reviewstorage": "redis://redis.redis:6379/5",
        "user": "redis://redis.redis:6379/6"
      },
      "service": {
        "castinfo": "cast-info:8080",
        "movieinfo": "movie-info:8080",
        "plot": "plot:8080",
        "reviewstorage": "review-storage:8080",
        "moviereview": "movie-review:8080",
        "userreview": "user-review:8080",
        "rating": "rating:8080",
        "composereview": "compose-review:8080",
        "user": "user:8080",
        "page": "page:8080"
      },
      "secret": "GT%j8S4GzJuha%oTM624rFPMSTfL@m&Q"
    }
  lb.json: |
    {
      "server": {
        "enable": false
      },
      "client": {
        "enable": false
      },
      "serverless": {
        "enable": false
      }
    }