apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: media-stats
  labels:
    release: prom
  namespace: media
spec:
  selector:
    matchLabels:
      microless: media
  endpoints:
  - port: stats
    interval: 5s
  namespaceSelector:
    matchNames:
    - media