apiVersion: v1
kind: Namespace
metadata:
  name: media-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
  namespace: media-test
data:
  config.json: |
    {
      "otel": "jaeger.jaeger:4317",
      "mongodb": {
        "url": "mongodb://mongodb.mongodb:27017",
        "database": "media"
      },
      "redis": {
        "moviereview": "redis://redis.redis:6379/0",
        "userreview": "redis://redis.redis:6379/1",
        "castinfo": "redis://redis.redis:6379/2",
        "movieinfo": "redis://redis.redis:6379/3",
        "plot": "redis://redis.redis:6379/4",
        "reviewstorage": "redis://redis.redis:6379/5",
        "user": "redis://redis.redis:6379/6"
      },
      "service": {
        "castinfo": "cast-info.media:8080",
        "movieinfo": "movie-info.media:8080",
        "plot": "plot.media:8080",
        "reviewstorage": "review-storage.media:8080",
        "moviereview": "movie-review.media:8080",
        "userreview": "user-review.media:8080",
        "rating": "rating.media:8080",
        "composereview": "compose-review.media:8080",
        "user": "user.media:8080",
        "page": "page.media:8080"
      },
      "gateway": "gateway.media:8080",
      "secret": "GT%j8S4GzJuha%oTM624rFPMSTfL@m&Q"
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: media-test
spec:
  template:
    spec:
      containers:
      - name: test
        image: waterlemongan/microless-media-test:0.3.0
        env:
        - name: TEST_CONFIG
          value: "/config/config.json"
        volumeMounts:
        - name: config-test
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config-test
          configMap:
            name: config-test
            items:
            - key: config.json
              path: config.json
      restartPolicy: Never
  backoffLimit: 0