apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: social-network
data:
  config.json: |
    {
      "grpc": ":8080",
      "rest": ":8081",
      "otel": "jaeger.jaeger:4317",
      "mongodb": {
        "url": "mongodb://mongodb.mongodb:27017",
        "database": "social-network"
      },
      "memcached": {
        "poststorage": "post-storage-memcached.social-network-backend:11211",
        "user": "user-memcached.social-network-backend:11211",
        "urlshorten": "url-shorten-memcached.social-network-backend:11211"
      },
      "redis": {
        "usertimeline": "redis://redis.social-network-backend:6379/0",
        "socialgraph": "redis://redis.social-network-backend:6379/1",
        "hometimeline": "redis://redis.social-network-backend:6379/2"
      },
      "service": {
        "poststorage": "post-storage:8080",
        "usertimeline": "user-timeline:8080",
        "user": "user:8080",
        "socialgraph": "social-graph:8080",
        "hometimeline": "home-timeline:8080",
        "media": "media:8080",
        "urlshorten": "url-shorten:8080",
        "usermention": "user-mention:8080",
        "text": "text:8080",
        "composepost": "compose-post:8080"
      },
      "secret": "gSZWnXKBt&2Yr@zaZ76sKzjbTqb4rbzR"
    }