apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    microless: social-network
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: ingress-gateway
    app.kubernetes.io/part-of: social-network
  name: ingress-gateway
  namespace: social-network
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    microless: social-network
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: k8s-deploy
    app.kubernetes.io/component: ingress-service
    app.kubernetes.io/part-of: social-network
  name: gateway
  namespace: social-network
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1
    route:
    - destination:
        host: gateway
        port:
          number: 8081
