apiVersion: v1
kind: Namespace
metadata:
  name: social-network
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit
  namespace: social-network
spec:
  limits:
  - default:
      cpu: "0.5"
      memory: 128Mi
    defaultRequest:
      cpu: "0.5"
      memory: 128Mi
    type: Container
