apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-vm-hpa
  namespace: social-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-vm
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: user
      metric:
        name: grpc_server_request_per_second
      target:
        type: AverageValue
        averageValue: "90"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
