apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-graph-hpa
  namespace: social-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-graph
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
