apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-graph-hpa
  namespace: social-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-graph
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: social-graph
      metric:
        name: grpc_server_request_per_second
      target:
        type: AverageValue
        value: "90"
