apiVersion: v1
kind: Service
metadata:
  name: rating
  labels:
    microless: media
  namespace: media
spec:
  ports:
  - port: 8080
    name: grpc
    targetPort: grpc
  - name: stats
    port: 9000
    targetPort: stats
  selector:
    microless: media
    app: rating
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
  labels:
    microless: media
  namespace: media
spec:
  selector:
    matchLabels:
      microless: media
      app: rating
  template:
    metadata:
      labels:
        microless: media
        app: rating
        type: vm
      name: rating
      namespace: media
    spec:
      containers:
      - name: server
        image: waterlemongan/microless-media-rating:0.3.0
        ports:
        - name: grpc
          containerPort: 8080
        - name: stats
          containerPort: 9000
        env:
        - name: SERVICE_CONFIG
          value: "/config/config.json"
        - name: LB_CONFIG
          value: "/config/lb.json"
        - name: SERVICE_ADDR
          value: ":8080"
        - name: STATS_ADDR
          value: ":9000"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            cpu: "0.5"
            memory: 50Mi
          requests:
            cpu: "0.5"
            memory: 50Mi
      volumes:
        - name: config
          configMap:
            name: config
            items:
            - key: config.json
              path: config.json
            - key: lb.json
              path: lb.json
